### ISSUE TITLE
Не хватает примеров куда что вводить...

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/GyverHub#1]
Я понимаю что библиотека новая, но сильно не хватает более развернутой инструкции желательно со скринами...

**Comment by GyverLibs** [comment]
Проект пока что даже не в открытом тестировании, это черновик)

**Comment by MalfurionST** [comment]
Ну тогда ждём полную версию, разобрался мне понравилось. 😁

**Comment by AlexGyver** [comment]
на hub.gyver.ru тестировал?

**Comment by MalfurionST** [comment]
Нет через андроид приложение

**Comment by AlexGyver** [comment]
а, я его залил на гит) забыл
