### ISSUE TITLE
Текст в выключателе Switch

### ISSUE THREAD

**Issue by waw555** [GyverLibs/GyverHub#10]
Здравствуйте!

Есть ли возможность переносить текст на новую строку в выключателе? Сейчас если текст длинный, то он уходит за границы экрана.

**Comment by GyverLibs** [comment]
Странно, вот в текущей версии переносится он
![image](https://github.com/GyverLibs/GyverHub/assets/84599917/e6fd2495-dbfc-4724-9cbb-5454c33382b7)

**Comment by KarlHanz** [comment]
Здравствуйте! 
Перестало "видеть" устройство в вебе и приложении. Версия приложения и библиотеки самые первые. По дате обновления файлов библиотеки на гитхабе стало ясно, что обновилась версия. 
После ручного правильного обновления библиотеки и приложения появились "тормоза" в десять и более секунд при обновлении индикаторов hub.LED, а также поля hub.Label. Очень долго подгружает устройство в приложении и вебе. До обновления всё работало идеально. Как откатить назад? 
Вытекает самый главный вопрос по дальнейшей эксплуатации - устройство планируется для автономной работы без присутствия человека рядом. В случае таких "обновлений" к устройству будет потерян контроль его управления, что недопустимо. Возможна ли эксплуатация на первых версиях библиотеки и приложения?
