### ISSUE TITLE
Проблема с бюиблиотекой GyverHub

### ISSUE THREAD

**Issue by AlexeiSukharev** [GyverLibs/GyverHub#11]
Здравствуйте. Установил все библиотеки согласно Wiki, пробую скомпилировать проект из примеров  full_demo.ino, при компиляции выходит вот такая ошибка
c:\Users\AdminLocal\Documents\Arduino\libraries\GyverHub\src\utils\misc.cpp: In function 'void GH_addEsc(String*, const void*, bool, char)':
c:\Users\AdminLocal\Documents\Arduino\libraries\GyverHub\src\utils\misc.cpp:73:13: error: 'memchr_P' was not declared in this scope
         if (memchr_P(cstr, '\"', len)) {
             ^~~~~~~~
c:\Users\AdminLocal\Documents\Arduino\libraries\GyverHub\src\utils\misc.cpp:73:13: note: suggested alternative: 'memchr'
         if (memchr_P(cstr, '\"', len)) {
             ^~~~~~~~
             memchr

exit status 1

Compilation error: exit status 1

Используется среда Arduino IDE  2.1.1 плата ESP32-cam в проекте выбрана плата AI-Thinker ESP32-CAM (выбрал так как с ней работает стандартный пример).
Подскажите пожалуйста в чем может быть проблема. Спасибо.

**Comment by GyverLibs** [comment]
Проблема в кривых руках разработчиков ядра esp32. В указанном файле замени memchr_P на memchr, в следующем обновлении добавлю у себя тоже
