### ISSUE TITLE
Тормоза после обновления библиотеки 

### ISSUE THREAD

**Issue by KarlHanz** [GyverLibs/GyverHub#12]
Здравствуйте!
При запуске перестало "видеть" устройство (на wemos d1 mini) в вебе и приложении. Версия приложения и библиотеки были самые первые. По дате обновления файлов библиотеки на гитхабе стало ясно, что обновилась версия библиотеки, а значит надо её обновить на устройстве. 
Устройство стало "видно" после ручного правильного обновления библиотеки (с дальнейшей перепрошивкой) и приложения, но появились "тормоза" в десять и более секунд при обновлении индикаторов hub.LED, а также поля hub.Label. Очень долго подгружает устройство в приложении и вебе. До обновления всё работало идеально. Как откатить назад?
Вытекает самый главный вопрос по дальнейшей эксплуатации - устройство планируется для автономной работы без присутствия человека рядом. В случае таких "обновлений" к устройству будет потерян контроль его управления, что недопустимо. Возможна ли стабильная эксплуатация на первых версиях библиотеки и приложения?

**Comment by GyverLibs** [comment]
назад откатить - никак, библиотека в раннем доступе и пока что дорабатывается. Приложение сейчас - временное и очень кривое, к релизу будет другое

**Comment by GyverLibs** [comment]
на всякий случай выложил свежее обновление (либа+сайт+аппа), у меня работает стабильно

**Comment by GyverLibs** [comment]
если нужно гарантировать работоспособность и неизменность версии - лучше использовать "приложение в памяти есп" в локальной сети

**Comment by KarlHanz** [comment]
Устройство, а это термостат для управления кондиционерами в серверной, управляется удалённо через телефон (компьютер), вариант подключаться непосредственно неприменим.

**Comment by GyverLibs** [comment]
"удалённо" - в локальной сети или MQTT?

**Comment by KarlHanz** [comment]
Через MQTT

**Comment by GyverLibs** [comment]
тогда не вариант да, ждать релиза. Попробуй текущую версию, не должно быть тормозов

**Comment by KarlHanz** [comment]
В ближайшее время ещё раз обновлю девайс на текущую версию либы. Спасибо!

**Comment by GyverLibs** [comment]
спасибо за репорт, к релизу отшлифуем так что блестеть будет)

**Comment by KarlHanz** [comment]
При попытке обновить прошивку файлом *.bin через кнопку FLASH ничего не происходит, раньше хоть и медленно, но отображался процесс заливки. Сейчас этот функционал доступен в обновлённой версии либы?

**Comment by GyverLibs** [comment]
Можно пример кода с led и label? Что там делается. У меня апдейты на led и label долетают без каких то задержек.

OTA по mqtt действительно сломалась, сегодня выпущу фикс

**Comment by KarlHanz** [comment]
https://github.com/KarlHanz/ACThermostat

**Comment by GyverLibs** [comment]
блин ну это портянка. Может получится выделить конкретный кусок, который стал работать хуже?

**Comment by GyverLibs** [comment]
проблема происходит при sendUpdate? Обновления приходят с бОльшим периодом, чем задано? Или в чём заключаются "тормоза"

кстати таймер на 10 мин можно запустить так: `GHtimer tmr(0, 0, 10);`

**Comment by GyverLibs** [comment]
я так понимаю [вот этот](https://github.com/KarlHanz/ACThermostat/blob/3fbb3c7d1537ed3719b0c51a93c32f8775a8d7c5/relayTemp_v0.82/relayTemp_v0.82.ino#L291-L315) блок выполняется со скоростью loop, соответственно при выходе температуры за границы - обновления начинают отправляться с максимальной частотой, по сути sendUpdate вызывается в loop. Так делать нельзя, это как раз приведёт к тормозам и кода и доставки сообщений, нужно отправлять по флагу либо встроить опять же таймер
```cpp
static GHtimer tmr(100);
if (tmr) {
  if (sw1 == 0 && (tempMdl >= sld1)) { //если средняя темп выше установленной
    relay1State = 1; //включить реле 1
    led1 = relay1State; //отобразить статус светодиодом
    hub.sendUpdate("led1", String(led1)); // обновляем led1
    digitalWrite(relay1, relay1State);
  }
  if (sw1 == 0 && (tempMdl < sld1)) { //если средняя темп ниже установленной
    relay1State = 0; //вЫключить реле 1
    led1 = relay1State; //отобразить статус светодиодом
    hub.sendUpdate("led1", String(led1)); // обновляем led1
    digitalWrite(relay1, relay1State);
  }

  if (sw2 == 0 && (tempMdl >= sld2)) { //если средняя темп выше установленной
    relay2State = 1; //включить реле 2
    led2 = relay2State; //отобразить статус светодиодом
    hub.sendUpdate("led2", String(led2)); // обновляем led2
    digitalWrite(relay2, relay2State);
  }
  if (sw2 == 0 && (tempMdl < sld2)) { //если средняя темп ниже установленной
    relay2State = 0; //вЫключить реле 2
    led2 = relay2State; //отобразить статус светодиодом
    hub.sendUpdate("led2", String(led2)); // обновляем led2
    digitalWrite(relay2, relay2State);
  }
}
```

также там выше в луп просто так создаются и складываются стринги, так тоже делать не стоит. Лучше пусть они создаются по факту отправки в телеграм, а не превентивно

**Comment by KarlHanz** [comment]
Alex, огромное спасибо за помощь, внесу правки в код с учётом твоих замечаний! Пусть мой пример послужит образцом как делать не надо))

**Comment by GyverLibs** [comment]
Надо в доку добавить, что обновления часто отправлять нельзя по понятным причинам (перегрузка сети, перегрузка mqtt брокера, процессор на 99% занят постоянной отправкой одного и того же итд)
