### ISSUE TITLE
Выравнивание текста в Tabs (Слева, По центру, Справа)

### ISSUE THREAD

**Issue by waw555** [GyverLibs/GyverHub#13]
Здравствуйте!

Можно ли сделать возможность выравнивания текста в Tabs, сейчас текст выравнивается по левой стороне, при  нескольких вкладках с маленьким названием было бы красивее выровнять по центру.

**Comment by GyverLibs** [comment]
привет, скорее всего нет. Либо по центру, либо возможность скроллинга по горизонтали пальцем, второе всё таки более полезно (попробую рассмотреть вариант при котором если вкладок мало - убирался скроллинг и добавлялось выравнивание по центру). Также вкладки не факт что останутся после релиза, вместо них есть более удобное выпадающее меню

**Comment by waw555** [comment]
На счет вкладок, спасибо что предупредили, жаль что возможно их не будет. Иногда переключить страницу с разными компонентами удобнее вкладкой, с главной страницы например, нежели переходить в меню. Если бы вместо вкладок можно было бы свайпом перелистнуть страницу в приложении как в книжке, было бы круто.

**Comment by GyverLibs** [comment]
Свайпы спорный вопрос, потому что как таковых "страниц" в панели управления нет, юзер может закодить всё что угодно. Можно несколько блоков вкладок на одной странице сделать, это тоже имеет место быть, например для настройки эффектов внутри эффектов или чего то такого. Но для меню - можно подумать, оно на странице заведомо одно

**Comment by waw555** [comment]
А Select не получает в var выбранное значение?

Хотел Tabs заменить на Select

**Comment by GyverLibs** [comment]
Получает конечно, порядковый номер от 0. Если кто то будет пользоваться табсами, я не буду их убирать, они не мешают остальным компонентам

**Comment by waw555** [comment]
Странно, при Tabs у меня switch отрабатывает изменения var, а при Select нет.

**Comment by GyverLibs** [comment]
Работает как часики
```cpp
uint8_t sel;

void build() {
    if (hub.Select(&sel, F("puk,kek,test"))) Serial.println(sel);
}
```
