### ISSUE TITLE
Обновление данные при переключении Select

### ISSUE THREAD

**Issue by waw555** [GyverLibs/GyverHub#15]
Здравствуйте!

При использовании следующей конструкции, не происходит обновление, точнее оно происходит не до конца, на Spinner текст 
меняется, а возможность изменять значение отсутствует, только после обновления страницы появляется возможность менять значение. Если в case добавить hub.refresh(); то все нормально. Правильно ли это, использовать обновление в case?
```
          hub.Title(F("Настройки"));
          hub.Select(&selMode, F("Автоматический,Ручной"), F("Температура"));
          switch(selMode){
            case 0:
              hub.Label_(F("updateTemp1"), valTemp1, F("Температура 1"));
              hub.Spinner(&hyst1, GH_FLOAT, F("Гистерезис 1"), 0, 10, 1);
            break;
            case 1:
              hub.Spinner(&temp2, GH_UINT8, F("Температура 2"), 0, 100, 1);
              hub.Spinner(&hyst2, GH_FLOAT, F("Гистерезис 2"), 0, 1, 0.1);
            break;
          }
```

**Comment by GyverLibs** [comment]
Привет, да, refresh можно вызывать откуда угодно и сколько угодно раз за билд, в документации об этом написано. Сигнал на обновление будет отправлен один раз после выхода из билдера. Рефреш тут нужен обязательно, без него работать не будет, потому что компоненты выводятся только при открытии панели управления, обновления по кнопке со стрелками, и при вызове refresh. Чтобы отобразить другие компоненты, которых не было на странице, нужно одно из трёх этих действий сделать
