### ISSUE TITLE
приложение на андроид временное, работает не на всех версиях, лучше пользоваться PWA

### ISSUE THREAD

**Issue by roman134123** [GyverLibs/GyverHub#17]
приложение на андроид временное, работает не на всех версиях, лучше пользоваться PWA

_Originally posted by @GyverLibs in https://github.com/GyverLibs/GyverHub/issues/6#issuecomment-1691625209_
            

Делаем управление поездом на макете железной дороги, без приложения никак не обойтись (

**Comment by GyverLibs** [comment]
Поэтому я и пишу про [веб приложение](https://github.com/GyverLibs/GyverHub/wiki/3.-%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5#%D0%B2%D0%B5%D0%B1-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-pwa), оно работает везде

**Comment by roman134123** [comment]
> Поэтому я и пишу про [веб-приложение](https://github.com/GyverLibs/GyverHub/wiki/3.-%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5#%D0%B2%D0%B5%D0%B1-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-pwa) , оно работает везде.

Все с того же смартфона: открыл веб https, установил приложение, в режиме WS работает только по HTTP. Хорошо, удалил приложение. Включил настройку в хроме как указано в инструкции (insecure-origin-as-secure) -> добавил http://hub.gyver.ru в список доверенных сайтов -> Enabled, подключился к вемосу, открыл (http://hub.gyver.ru), установил приложение, нажал на шестеренку, в разделе WS обновил IP телефона, префикс совпадает с заданным в прошивке, нажимаю на лупу и ничего не обнаружено. Что делаю не так?

**Comment by GyverLibs** [comment]
не знаю, у меня работает

**Comment by Serega88kos** [comment]
> > Поэтому я и пишу про [веб-приложение](https://github.com/GyverLibs/GyverHub/wiki/3.-%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5#%D0%B2%D0%B5%D0%B1-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-pwa) , оно работает везде.
> 
> Все с того же смартфона: открыл веб https, установил приложение, в режиме WS работает только по HTTP. Хорошо, удалил приложение. Включил настройку в хроме как указано в инструкции (insecure-origin-as-secure) -> добавил http://hub.gyver.ru в список доверенных сайтов -> Enabled, подключился к вемосу, открыл (http://hub.gyver.ru), установил приложение, нажал на шестеренку, в разделе WS обновил IP телефона, префикс совпадает с заданным в прошивке, нажимаю на лупу и ничего не обнаружено. Что делаю не так?

может не до конца настроил?
у меня тоже один пользователь ругался, что не работает, а выяснилось, что не все настроил)
https://github.com/GyverLibs/GyverHub/wiki/3.-%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC%D0%B0-ws

**Comment by Serega88kos** [comment]
Саня, можно как-то оставить сообщение об успешном обновлении или нет?)
Чтобы не сидеть в ожидании чуда, а вернуться к монитору или к вкладке и увидеть, что же произошло...
DONE исчезает быстро)
Рядом с IDLE или подтверждать окно об статусе операции)

**Comment by roman134123** [comment]
> > > Поэтому я и пишу про [веб-приложение](https://github.com/GyverLibs/GyverHub/wiki/3.-%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5#%D0%B2%D0%B5%D0%B1-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-pwa) , оно работает везде.
> > 
> > 
> > Все с того же смартфона: открыл веб https, установил приложение, в режиме WS работает только по HTTP. Хорошо, удалил приложение. Включил настройку в хроме как указано в инструкции (insecure-origin-as-secure) -> добавил http://hub.gyver.ru в список доверенных сайтов -> Enabled, подключился к вемосу, открыл (http://hub.gyver.ru), установил приложение, нажал на шестеренку, в разделе WS обновил IP телефона, префикс совпадает с заданным в прошивке, нажимаю на лупу и ничего не обнаружено. Что делаю не так?
> 
> может не до конца настроил? у меня тоже один пользователь ругался, что не работает, а выяснилось, что не все настроил) https://github.com/GyverLibs/GyverHub/wiki/3.-%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC%D0%B0-ws

Вновь сделал все поэтапно, как тут описано (вашей ссылке), не может найти вемос. Заметил странную вещь: когда месяц назад игрался с GyverHub в приложении на андроид залетала мгновенно, ничего не обновлял вручную, все само подтягивалось, соответственно, в приложении оставались сохраненными два вемоса, с которыми игрался. Попробовал их удалить из списка после открытия приложения на андроиде, удалил, вновь пытаюсь подключиться к новому вемосу, проверил все: и префикс, и IP смартфона, который подключен - не ищется новый вемос, попробовал другой вемос, зашил его, та же история. Удалил приложение андроид с смартфона; далее вновь и вновь делал все по инструкции по веб-приложению, ничего в поиске не выдает. И решил снова поставить андроид приложение, ведь месяц назад то все ок было, без таких танцев с бубном. Открыл приложение андроид после установки и снова вижу те же два устройства, с которыми игрался месяц назад. Почему они подтянулись, если удалял их? Чистил кэш на смартфоне и данные приложения - после переустановки все равно в списке остаются те два вемоса месячной давности... В этом может быть причина моей проблемы с поиском вемоса?

**Comment by n0rdling** [comment]
Приложение на андроиде и веб-приложение не подключается к MQTT HOST: srv2.clusterfly.ru, порт wss: 9994 (пробовал и другие: 9991, 9992, 9993), причем wemos подключился благополучно по tcp:9991. Логин и пароль введен из профиля clusterfly.ru, Prefix = логин, Client ID - придумал свой. Что-то делаю не так?
