### ISSUE TITLE
HA + local mosquitto + GyverHub

### ISSUE THREAD

**Issue by tebenkov2222** [GyverLibs/GyverHub#18]
Не могу отправить данные в ESP с Home assistant через локальный Mosquitto
- HA и MQTT развернуты у меня не сервере локально с помощью docker compose + debian
- в HA настроил подключение к mqtt - Подключение есть и оно работает.
- В приложении GyverHub получил id устройства (871fb4c2). 
- Данные в Mosquitto я проверяю через приложение MQTT Explorrer
- Получаю данные через get топик (MyDevices/hub/871fb4c2/get/Switch1). Данные приходят верные. тут все ок (хотя есть моменты но думаю я их поборю) (для получения данных через топик вызывал метод hub.sendGetAuto(true) в build). Теперь при изменении переключателя в приложении он меняется в mosquitto (и можно получить в ha)
- Пытаюсь обновить данные через set топик (MyDevices/871fb4c2/set/Switch1). В mosquitto он меняется однако никакой реакции со стороны контроллера нет. Пытался разными способами. И через gui методы и через пустышку Dummy_. Что в первом, что во втором случае никакой реакции контроллера нет.
Arduino Code:
```
#include <GyverHub.h>
GyverHub hub("MyDevices", "TestEsp", "");  // префикс, имя, иконка
bool swtch;
int curMillis = 0;
int16_t var = 5;
// билдер
void build() {
  hub.Switch_(F("Switch1"), &swtch);
  hub.sendGetAuto(true);
}
void setup() {
    Serial.begin(115200);
    pinMode(LED_BUILTIN, OUTPUT);
    // подключение к WiFi...
    // настройка MQTT
    WiFi.mode(WIFI_STA);
    WiFi.begin("Keenetic", "Xiaomi12345");
    Serial.println("Setup");
    while (WiFi.status() != WL_CONNECTED) {
      delay(500);
      Serial.print(".");
    }
    hub.setupMQTT("192.168.1.64", 1883, "admin", "admin");

    hub.onBuild(build);     // подключаем билдер
    hub.begin();            // запускаем систему
    Serial.println("");
    Serial.println("Begin");
}

void loop() {
  if (millis() - curMillis >= 5000) {  // ищем разницу
    curMillis = millis();
    swtch = !swtch;
    hub.sendGet("Switch1");
    Serial.println("Change switch");
  }
  Serial.print("Switch = ");
  Serial.println(swtch);
  digitalWrite(LED_BUILTIN, swtch);

  hub.tick();  // обязательно тикаем тут
}
```
HA configuration

```
mqtt:
  switch:
    - name: testesp
      state_topic: "MyDevices/hub/871fb4c2/get/Switch1"
      command_topic: "MyDevices/871fb4c2/set/Switch1"
      payload_on: "1"
      payload_off: "0"
```
`

**Comment by tebenkov2222** [comment]
Буду рад любой помощи. Если смогу побороть проблему то отпишу решение

**Comment by GyverLibs** [comment]
кажется есть ошибка в коде библиотеки, секунду

**Comment by GyverLibs** [comment]
Нет возможности протестировать, но вот так должно работать. С обновлением добавлю фикс в основную версию
[GyverHub.zip](https://github.com/GyverLibs/GyverHub/files/12500180/GyverHub.zip)

**Comment by tebenkov2222** [comment]
Спасибо. Протестирую - отпишу

**Comment by tebenkov2222** [comment]
Библиотека что вы отправили: Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: reading directory C:\Users\Admin\AppData\Local\Temp\2211312604\GyverHub.h content: %!!(MISSING)w(*fs.PathError=&{readdir C:\Users\Admin\AppData\Local\Temp\2211312604\GyverHub.h 3})
При всем этом старая открылась нормально

**Comment by GyverLibs** [comment]
нужно достать из архива файл и заменить им тот который сейчас в папке src библиотеки

**Comment by tebenkov2222** [comment]
Заработало, спасибо!

**Comment by GyverLibs** [comment]
огонь
