### ISSUE TITLE
не находит устойство

### ISSUE THREAD

**Issue by ghost** [GyverLibs/GyverHub#19]

**Comment by ultragamesik** [comment]
c яндекс браузером вроде работает, но желательно хром. если есть кто знает в чем причина помогите.

**Comment by GyverLibs** [comment]
Стандартные примеры работают?

**Comment by ghost** [comment]
Да, basic.ino работает.
Что не так в моем коде? Я со вчерашней ночи пытаюсь что то сделать...

**Comment by GyverLibs** [comment]
Значит ищи ошибки в этом полотне. Частями комментируя код пока не заработает

**Comment by ghost** [comment]
Буду пытаться.

(Мой ПК который 4гб озу 4 ядра игровая видеокарта - нееет я буду это все компилировать...)

**Comment by ghost** [comment]
А можете дать пример для MQTT?

**Comment by GyverLibs** [comment]
Почти все встроенные примеры настроены на mqtt

**Comment by ghost** [comment]
Хорошо, спасибо.

**Comment by ghost** [comment]
а я в примерах видел какой то hub.pass что это? это чтобы вводить пароль?

**Comment by GyverLibs** [comment]
`Pass` это компонент ввода пароля. Такой же как `Input`, но ввод скрыт звёздочками
