### ISSUE TITLE
Ждём

### ISSUE THREAD

**Issue by da3020** [GyverLibs/GyverHub#2]
...Я так понимаю, эта чудная штука ещё не доcтупна через менеджер библиотек Arduino IDE?

**Comment by GyverLibs** [comment]
Эта штука в разработке, пока проходите мимо и подписывайтесь на ТГ канал с обновлениями)

**Comment by Crazy-Max-Blog** [comment]
А видео будет?

**Comment by GyverLibs** [comment]
@Crazy-Max-Blog когда нибудь)

**Comment by Crazy-Max-Blog** [comment]
Я конечно понимаю, что библиотека в разработке, но куда писать id (к примеру HUB_2a3356) в веб-приложении?

**Comment by GyverLibs** [comment]
В ридми не просто так написано проходить мимо. На гитхабе лежит самая старая версия библиотеки, она несовместима с веб приложением

**Comment by MalfurionST** [comment]
Здравствуйте, но уже давно дразните этой библиотекой, обновите альфу очень хочется по счупать (пусть даже сырую)... 😁

**Comment by GyverLibs** [comment]
Дело не в очень сырости. Ядро постоянно переписывается, и так как веб сервис всегда актуальной версии - не актуальная библиотека просто перестанет работать. Как только буду понимать что всё работает стабильно - приглашу всех тестировать и добавлю примеры. Сейчас всё в слишком активной разработке, а выкатывать ночные билды нет сил. Плюс там есть зависимость от ещё одной библиотеки, которая пока не вышла в релиз и тоже пока меняется часто

**Comment by MalfurionST** [comment]
А приложение под телефон надеюсь останется, помимо веб интерфейса?..

**Comment by GyverLibs** [comment]
Веб версию можно установить как PWA  приложение на любое устройство (android, ios, windows, linux). Полноценного приложения скорее всего не будет, а если будет - то очень сильно позже, либо если кто то возьмётся его делать

**Comment by MalfurionST** [comment]
Жалко.... будем ждать....

**Comment by GyverLibs** [comment]
хорошие новости - нативное приложение на андроид будет, причём одновременно с открытой бетой сервиса. Скорее всего даже с чуть большими возможностями в плане подключения, чем веб версия

**Comment by MalfurionST** [comment]
Здравствуйте, знаю что это творческий процесс, но хотя бы ожидаемые даты выхода беты, хотя бы какой месяц?...

**Comment by GyverLibs** [comment]
Как минимум май

**Comment by GyverLibs** [comment]
Отличные новости. После очередного переписывания ядра система стала работать стабильно, есп больше не крашится, всё свистит пердит и работает изумительно. В ближайшие дни можно ожидать версию для тестирования

**Comment by GyverLibs** [comment]
Потихоньку оформляю вики и базовые примеры https://github.com/GyverLibs/GyverHUB/wiki 
По бета тестированию будем собираться тут https://github.com/GyverLibs/GyverHUB/issues/3

**Comment by GyverLibs** [comment]
актуальные версии с примерами загружены, можно тестить. Документацию по началу работы допишу по мере возможностей

**Comment by IljaGolenev** [comment]
Я только глаза открыл... Я все ещё сплю, или ещё и приложение под это дело будет?  Где искать?

**Comment by GyverLibs** [comment]
Сайт можно установить как pwa приложение на любое устройство

**Comment by IljaGolenev** [comment]
Флюс мне в ус! Это будет народный hub!

**Comment by GyverLibs** [comment]
Не то слово)

**Comment by mihailnik** [comment]
?1. эта библиотека умеет автоматически открывать страницу при подключении к ESP8266 в режиме WIFI_AP ?
Кажется captive portal называется. А то приходится ip в браузере писать.  #define GH_INCLUDE_PORTAL прописал но не перебрасывает на страницу.
?2. Gyver Portal уже не будет развиваться? правильно ли я мыслю что нужно HUB изучать вместо Portal?

**Comment by GyverLibs** [comment]
1. Вроде само по себе должно работать. Если не перекидывает - гляну, возможно нужно поднимать dns сервер
2. Hub несравнимо лучше по всем параметрам, за исключением возможности создать страницу любой нужной конфигурации, тут только готовые блоки. Если модульность устраивает - конечно лучше использовать хаб
