### ISSUE TITLE
NodeMCU 3.0 pin 10/9

### ISSUE THREAD

**Issue by tebenkov2222** [GyverLibs/GyverHub#20]
Не могу использовать пины 9 и 10 на плате Nodemcu 3 0 Esp8266. При использовании 10 (S3) пина ничего не происходит ( в качестве выхода). При использовании 9 (S2) пина выходит ошибка 
```
wdt reset
load 0x4010f000, len 3424, room 16 
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v000760c0
~ld
```

Возможно эти пины уже заняты библиотекой. Хотел уточнить так это или нет?

И, возможно заняты пины под spi или какие другие. Хотелось бы иметь понимание что можно использовать а что нет

**Comment by GyverLibs** [comment]
Читайте документацию на nodemcu/esp8266. Пины с 6 по 11 использовать нельзя, к ним подключена память
