### ISSUE TITLE
mqtt error

### ISSUE THREAD

**Issue by ghost** [GyverLibs/GyverHub#21]
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/4ce87d63-641d-4e2c-b67f-ec29426db412)

hub.setupMQTT("m8.wqtt.ru", 13709, "********", "*******");

ошибка mqtt, я правильно сделал что добавил логин и пароль?

**Comment by GyverLibs** [comment]
так сделал?
![image](https://github.com/GyverLibs/GyverHub/assets/84599917/44c4803f-dc01-4e59-9835-c4345f0d23d1)

**Comment by ghost** [comment]
нет я вебсокет написал в сайте и в скетче, сейчас исправлю

**Comment by ghost** [comment]
а пароль и логин нужны в скетче?

**Comment by GyverLibs** [comment]
конечно

**Comment by ghost** [comment]
исправил, сейчас проверю

**Comment by ghost** [comment]
работает, спасибо что ты написал такую крутую библиотеку и сайт!

**Comment by GyverLibs** [comment]
![image](https://github.com/GyverLibs/GyverHub/assets/84599917/f2daaa0e-68d1-480e-ab24-28ac5cecc138)

**Comment by GyverLibs** [comment]
всегда пожалуйста
