### ISSUE TITLE
Init Mqtt sensors

### ISSUE THREAD

**Issue by tebenkov2222** [GyverLibs/GyverHub#22]
Хотелось бы иметь возможность проинициализировать данные в mqtt при запуске контроллера (может быть в сетап или при первом вызове `hub.sendGetAuto(true);` ), так как сейчас пришлось закостылить проверку первого цикла в котором в котором я отправляю все данные в топики. Обязательно он должен быть после `hub.tick()` так как если поставить до, то топики не обновятся.
Выглядит костыль вот так:
```
bool firstBuild = false;
void checkFirstBuild(){
  if(!firstBuild){
    firstBuild = true;
    updateGetSensors();
  }
}
void updateGetSensors(){
  Serial.print("updateGetSensors");
  hub.sendGet("SensorUp");
  hub.sendGet("LightGlobal");
  hub.sendGet("MotorDrive");
  hub.sendGet("MotorReverse");
}
void loop() {
  hub.tick();  // обязательно тикаем тут
  checkFirstBuild();
}
```
Еще момент. Если указать последовательно имена в sendGet то будет вот такой прикол:
```
void updateGetSensors(){
  Serial.print("updateGetSensors");
  hub.sendGet("SensorUp,LightGlobal,MotorDrive,MotorReverse");
}
```
![image](https://github.com/GyverLibs/GyverHub/assets/52998392/c7bcfd52-f18b-4866-bf4d-735af82fcdfb)

**Comment by GyverLibs** [comment]
отправлять данные на MQTT не имеет смысла, пока контроллер не подключился к серверу. Поэтому лучше вызывать не после tick, а подключить обработчик onEvent и ловить событие MQTT CONNECTED, и по нему отправлять свои апдейты
```cpp
  hub.onEvent([](GHevent_t event, GHconn_t from){
    if (event == GH_CONNECTED && from == GH_MQTT) {
      // отправить
    }
  });
```

**Comment by GyverLibs** [comment]
прикол не понял - пришли некорректные данные? А если раздельно отправлять - приходит правильно?

**Comment by tebenkov2222** [comment]
По ивенту спасибо!

По данным. Если отправлять раздельно то приходит нормально:
![image](https://github.com/GyverLibs/GyverHub/assets/52998392/27ffe11b-b2d3-450b-91f9-0d4793ed09d0)

**Comment by GyverLibs** [comment]
да, есть ошибка в коде, сейчас выпущу обновление. Нужно будет перекачать файл GyverHub.h

**Comment by GyverLibs** [comment]
готово

**Comment by tebenkov2222** [comment]
Обновление заработало, спасибо
