### ISSUE TITLE
медленный mqtt

### ISSUE THREAD

**Issue by ghost** [GyverLibs/GyverHub#23]
я жму на кнопку которая обновляет значение в лейбл, лейбл обнавляется но с большой задержкой

**Comment by GyverLibs** [comment]
либо криво запрограммировано, либо используется медленный публичный MQTT сервер

**Comment by ghost** [comment]
я думаю что дело в медленном сервере, а где взять быстрый?

**Comment by GyverLibs** [comment]
либо поднять свой, либо использовать какой нибудь платный, либо искать другой бесплатный. В документации [приведён](https://github.com/GyverLibs/GyverHub/wiki/2.-%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B#mqtt) список бесплатных брокеров

**Comment by GyverLibs** [comment]
если у тебя wqtt плохо работает - проблема где то в коде

**Comment by ultragamesik** [comment]
`#ifdef GH_ESP_BUILD
  WiFi.mode(WIFI_STA);
  WiFi.begin(AP_SSID, AP_PASS);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();
  Serial.println(WiFi.localIP());

  hub.setupMQTT("m8.wqtt.ru", 13706, "u_44RHJV", "H9S8BbdR");
#endif

  // обработчик билда
  hub.onBuild(build);

  // обработчик текста из веб-консоли
  hub.onCLI([](String & s) {
    Serial.println(s);
    hub.print(s);   // отправить эхо
    // hub.print(s, GH_RED);
  });

  // обработчик статуса для отладки
  hub.onEvent([](GHevent_t event, GHconn_t from) {
    // GHreadXXXX берёт текстовое описание статуса из PROGMEM
    Serial.print(GHreadConn(from));
    Serial.print(": ");
    Serial.println(GHreadEvent(event));
  });

  // вывести причину перезагрузки
  hub.onReboot([](GHreason_t r) {
    Serial.println(GHreadReason(r));
  });

  // добавить поля в Info
  hub.onInfo([](GHinfo_t info) {
    switch (info) {
      case GH_INFO_VERSION:
        hub.addInfo(F("Custom_ver"), F("v1.5"));
        break;
      case GH_INFO_NETWORK:
        hub.addInfo(F("Custom_net"), "net value");
        break;
      case GH_INFO_MEMORY:
        hub.addInfo(F("Custom_mem"), String(123));
        break;
      case GH_INFO_SYSTEM:
        hub.addInfo(F("Custom_sys"), "text");
        break;
    }
  });`
здесь есть ошибка?

**Comment by GyverLibs** [comment]
многострочный код - три символа ``` надо писать

**Comment by GyverLibs** [comment]
убери всё лишнее, оставь минимальный пример

**Comment by ghost** [comment]
когда я выхожу из esp8266 потом обновляю страницу и заново захожу происходит unfocus focus, и данные обновляются
но это почему то не происходит без перезахода.

**Comment by GyverLibs** [comment]
опиши последовательность действий, может это недоработка в библиотеке

**Comment by ghost** [comment]
нажатие на кнопку
выход в меню выбора устройств
обновление страницы
вход в esp8266
и теперь значение обновляется

**Comment by GyverLibs** [comment]
какое значение, где? Как выглядит скетч?

**Comment by ultragamesik** [comment]
// быстрый старт

#include <Arduino.h>

// логин-пароль WiFi

#define GH_INCLUDE_PORTAL

#define AP_SSID ""
#define AP_PASS ""

#define AL_PASS "helloug123"

// подключаем библиотеку и настраиваем устройство
#include <GyverHub.h>
GyverHub hub("MyDevices", "ESP8266", "");
// иконки
// https://fontawesome.com/v5/cheatsheet/free/solid
// https://fontawesome.com/v5/search?o=r&m=free&s=solid

// переменные для интерфейса
GHbutton engine;
GHbutton headlight;
String inp_str = "";

// ugl

String es = "Off";
String led = "Off";
String err = "OK";

// bat
// const int analogPin = A0;  // Аналоговый пин, к которому подключен делитель напряжения
// const float dividerRatio = 10.0;  // Соотношение делителя напряжения (R2 / (R1 + R2))
// const float fullVoltage = 12.6;  // Напряжение при полностью заряженных аккумуляторах (3 * 4.2 В)
// const float emptyVoltage = 9.0;  // Напряжение при разряженных аккумуляторах (3 * 3.0 В)
// int rawValue;
// float voltage;
// float chargePercentage = 100.0;
float volt = 12.6;

// это наш билдер. Он будет вызываться библиотекой
// для сборки интерфейса, чтения значений и проч.
void build() {
    // сделаем интерфейс в виде стильных виджетов
    // BeginWidgets() начинает новую горизонтальную строку виджетов
    hub.BeginWidgets();

    // ширина следующих виджетов задаётся в %
    hub.WidgetSize(50);

    // это кнопка без настроек
    // Кнопка - активный компонент: вернёт 1 если нажата
    // if (hub.Button()) Serial.println("Button 1 press");

    // ко второй кнопке подключим переменную b2
    // она будет true, пока кнопка удерживается. Опросим её ниже в loop
    // добавим название и цвет
    hub.Button(&engine, F("ENGINE"), GH_GREEN);
    hub.Button(&headlight, F("LED"), GH_YELLOW);
    
    // сменим ширину на 50%
    hub.WidgetSize(100);

    // Label - пассивный компонент, он не возвращает результата действия
    // пусть он выводит актуальный millis() при загрузке страницы
    // hub.Label(String(millis()), F("millis label"));

    // сделаем ещё один label с личным именем, к функции добавится _
    // ниже в loop будем отправлять обновления на его имя
    hub.Label_(F("ens"), String(es), F("ENGINE S"));
    hub.Label_(F("led"), String(led), F("LED S"));
    hub.Label_(F("err"), String(err), F("ERROR"));
    hub.Label_(F("bat"), String(volt), F("BAT CHARGE"));
    // добавим слайдер шириной 100, во всю строку
    // hub.WidgetSize(100);

    // к этому слайдеру не подключена переменная, но мы можем
    // вывести значение, которое отправено на его имя
    // Слайдер -активный компонент, вернёт true при изменении значения
    // if (hub.Slider()) {
    //     Serial.print("Slider1 value: ");
    //     Serial.println(hub.action().valueInt());  // получим как целое число
    // }

    // добавим ещё два слайдера и подключим переменные. Система будет сама обновлять в них значения!
    // нужно передать адрес переменной и её точный тип
    // у слайдера также есть минимум, максимум, шаг и цвет
    // if (hub.Slider(&sld_r, GH_INT, F("Red"), 0, 255, 1, GH_RED)) {}
    // if (hub.Slider(&sld_g, GH_INT, F("Green"), 0, 255, 1, GH_GREEN)) {}
    // if (hub.Slider(&sld_b, GH_INT, F("Blue"), 0, 255, 1, GH_BLUE)) {}
        // переменная уже обновилась и новое значение доступно во всей области определения
    // if (hub.Slider(&sld_f, GH_FLOAT, F("Slider F"), 0.0, 1.0, 0.01, GH_PINK)) {
    //     Serial.print("Slider3 value: ");
    //     Serial.println(sld_f);
    // }

    // добавим заголовок. Он также закроет предыдущую строку виджетов
    // hub.Title(F("Input"));
    
    // кстати, установка ненулевого значения ширины также 
    // автоматически создаст виджет после заголовка
    hub.WidgetSize(100);

    // Компонент Input может работать переменнми любых типов и автоматически переписывать в них значение!
    // попробуем с String, char[] и int
    // для char[] нужно обязательно указать размер массива, чтобы не превысить его, что приведёт к сбою программы!!
    hub.Input(&inp_str, GH_STR, F("PASSWORD"));
    // hub.Input(&inp_cstr, GH_CSTR, F("cstring input"), 10);      // <- 10 - макс. длина строки
    // hub.Input(&inp_int, GH_INT16, F("int input"), 0, F("^\\d{4}$"));  // + regex на 4 цифры

    // что будет, если не создавать строку виджетов через BeginWidgets()?
    // закончим отрисовку виджетов
    hub.EndWidgets();
    
    // и выведем пару компонентов
    // hub.Switch();
    
    // они выведутся вертикальным списком!
}

void setup() {
    Serial.begin(115200);
    pinMode(4, OUTPUT);
    pinMode(5, OUTPUT);
    // если это ESP - подключаемся к WiFI
#ifdef GH_ESP_BUILD
  WiFi.mode(WIFI_STA);
  WiFi.begin(AP_SSID, AP_PASS);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();
  Serial.println(WiFi.localIP());

  hub.setupMQTT("m8.wqtt.ru", 13706, "u_44RHJV", "H9S8BbdR");
#endif

  // обработчик билда
  hub.onBuild(build);

  // обработчик текста из веб-консоли
  hub.onCLI([](String & s) {
    Serial.println(s);
    hub.print(s);   // отправить эхо
    // hub.print(s, GH_RED);
  });

  // обработчик статуса для отладки
  hub.onEvent([](GHevent_t event, GHconn_t from) {
    // GHreadXXXX берёт текстовое описание статуса из PROGMEM
    Serial.print(GHreadConn(from));
    Serial.print(": ");
    Serial.println(GHreadEvent(event));
  });

  // вывести причину перезагрузки
  hub.onReboot([](GHreason_t r) {
    Serial.println(GHreadReason(r));
  });

  // добавить поля в Info
  hub.onInfo([](GHinfo_t info) {
    switch (info) {
      case GH_INFO_VERSION:
        hub.addInfo(F("Custom_ver"), F("v1.5"));
        break;
      case GH_INFO_NETWORK:
        hub.addInfo(F("Custom_net"), "net value");
        break;
      case GH_INFO_MEMORY:
        hub.addInfo(F("Custom_mem"), String(123));
        break;
      case GH_INFO_SYSTEM:
        hub.addInfo(F("Custom_sys"), "text");
        break;
    }
  });

    hub.onBuild(build);     // подключаем билдер
    hub.begin();            // запускаем систему
// #ifdef GH_ESP_BUILD
//   WiFi.mode(WIFI_STA);
//   WiFi.begin(AP_SSID, AP_PASS);
//   while (WiFi.status() != WL_CONNECTED) {
//     delay(500);
//     Serial.print(".");
//   }
//   Serial.println();
//   Serial.println(WiFi.localIP());

//   hub.setupMQTT("m8.wqtt.ru", 00000, "", "");
// #endif

//   // обработчик билда
//   hub.onBuild(build);

//   // обработчик текста из веб-консоли
//   hub.onCLI([](String & s) {
//     Serial.println(s);
//     hub.print(s);   // отправить эхо
//     // hub.print(s, GH_RED);
//   });

//   // обработчик статуса для отладки
//   hub.onEvent([](GHevent_t event, GHconn_t from) {
//     // GHreadXXXX берёт текстовое описание статуса из PROGMEM
//     Serial.print(GHreadConn(from));
//     Serial.print(": ");
//     Serial.println(GHreadEvent(event));
//   });

//   // вывести причину перезагрузки
//   hub.onReboot([](GHreason_t r) {
//     Serial.println(GHreadReason(r));
//   });

//   // добавить поля в Info
//   hub.onInfo([](GHinfo_t info) {
//     switch (info) {
//       case GH_INFO_VERSION:
//         hub.addInfo(F("Custom_ver"), F("v1.5"));
//         break;
//       case GH_INFO_NETWORK:
//         hub.addInfo(F("Custom_net"), "net value");
//         break;
//       case GH_INFO_MEMORY:
//         hub.addInfo(F("Custom_mem"), String(123));
//         break;
//       case GH_INFO_SYSTEM:
//         hub.addInfo(F("Custom_sys"), "text");
//         break;
//     }
//   });
}


void loop() {
    hub.tick();  // обязательно тикаем тут

    if (engine) {
        static GHtimer tmr(500);
        if (tmr.ready()) {
          if (inp_str == AL_PASS){
            err = "none";
            if (es == "Off"){
              digitalWrite(4, HIGH);
              es = "On";
              Serial.println("Engine On");
            } else if (es == "On") {
              digitalWrite(4, LOW);
              es = "Off";
              Serial.println("Engine Off");
            }
          }
        }
    }
    if (headlight) {
        static GHtimer tmr(500);
        if (tmr.ready()) {
          if (inp_str == AL_PASS){
            err = "none";
            if (led == "Off"){
              digitalWrite(5, HIGH);
              led = "On";
              Serial.println("LED On");
            } else if (led == "Off") {
              digitalWrite(5, LOW);
              led = "Off";
              Serial.println("LED Off");
            }
          }
        }
    }
    if (inp_str == AL_PASS) {
      err = "OK";
    } else if (inp_str == "") {
      err = "Enter password";
    } else if (inp_str != AL_PASS) {
      err = "Invalid password!";
    }
    // if (b2.changed()) Serial.println(b2 ? "b2 press" : "b2 release");
    // rawValue = analogRead(analogPin);
    // voltage = (rawValue / 1023.0) * 3.3 * dividerRatio;
    // chargePercentage = map(voltage, emptyVoltage, fullVoltage, 0, 100);
    // chargePercentage = constrain(chargePercentage, 0, 100);

    // обновим лейбл с именем lbl по таймеру на 1 секунду
    hub.sendUpdate("ens");
    hub.sendUpdate("led");
    hub.sendUpdate("err");
    hub.sendUpdate("bat");
    // значение будет прочитано внутри билдера, а там у нас millis()
}

**Comment by ghost** [comment]
значение лейбла (текст лейбла, но в сериал выводит что кнопка сработала)

**Comment by GyverLibs** [comment]
я не могу изучать код в таком виде. Многострочный код нужно помещать в тег ```

**Comment by GyverLibs** [comment]
у тебя sendUpdate прямо в loop? Это не будет работать. Либо по таймеру, либо по факту

**Comment by ghost** [comment]
да, в loop, сейчас помещю его туда когда надо его выполнить

**Comment by D4n13l3k00** [comment]
Купил ESP8266, пользуюсь через wqtt, интеграция с Алисой, работает практически моментально.
Тут скорее всего прикол в коде, брокер ни при чем

**Comment by ghost** [comment]
https://pastebin.com/M2B03fJJ
посмотри код @GyverLibs 
я не смог сделать чтобы работало, в чем моя ошибка?

**Comment by GyverLibs** [comment]
Ни малейшего понятия, тут несколько сотен строк и половина законмментирована. Попробуй на минимальном примере, потом расширяй код. Нельзя сразу большое полотно писать, нужно потихоньку с отладкой

**Comment by ghost** [comment]
дай basic.ino чтобы работало с mqtt
ну мне 13 лет, сделал как то так

**Comment by GyverLibs** [comment]
Любой встроенный пример открой, делать ничего не нужно

**Comment by ghost** [comment]
full demo работает, пойду его переделовать под мой электровелосипед

**Comment by ultragamesik** [comment]
а как скопировать иконки из fontawesome?
