### ISSUE TITLE
блокировка switchIcon

### ISSUE THREAD

**Issue by ghost** [GyverLibs/GyverHub#24]
можно ли сделать так чтобы я вводил пароль, после этого можно было нажимать на SwitchIcon
и чтобы я мог нажать кнопку заблокировать и у меня снова просило пароль перед нажатием

**Comment by GyverLibs** [comment]
Можно, но довольно сложно. Нужно по сути вести в памяти базу данных, какие клиенты ввели пароль правильный, и при запросе интерфейса вручную проверять доступен ли им свитч и выводить его если да

**Comment by ghost** [comment]
прочитал около 3-х раз но ничего не понял.

**Comment by ghost** [comment]
короче говоря, без пароля. (пока что)

**Comment by GyverLibs** [comment]
Я поэтому и пишу, что сложно)

**Comment by ghost** [comment]
причина закрытия - СЛОЖНО

**Comment by ghost** [comment]
А если я поставлю в переменную switch false тесли будет неверный пароль?
если переменная равна true я буду проверять если пароль верный тогда то что я хочу а если неверный тогда поставлю switch = false; ?

**Comment by GyverLibs** [comment]
ничего не понял)

**Comment by ghost** [comment]
а как узнавать когда нажимают на свич?
`if (switch) {}`
ну как с кнопками

**Comment by GyverLibs** [comment]
Так же как у любого активного компонента

**Comment by ghost** [comment]
можно пример?

**Comment by GyverLibs** [comment]
Пример basic

**Comment by ghost** [comment]
if (switch.changed()) {}

**Comment by ghost** [comment]
так?

**Comment by GyverLibs** [comment]
Нет

**Comment by ghost** [comment]
А можно ли как нибудь сменить вид свича на выкоюченный через скетч? Чтобы я смог одним нажатием на кнопку выключить все свичи

**Comment by GyverLibs** [comment]
Конечно, по нажатию на кнопку обнулить переменные свитчей и запросить hub.refresh()

**Comment by ghost** [comment]
Это хорошо)

**Comment by ghost** [comment]
Я хочу сделать панель управления электровелосипедом, а потом может и шеринг электровелосипедов в Армении открою.

**Comment by ghost** [comment]
я написал hub.refresh(); но он срабатовает после перезахода на устройство ESP8266

**Comment by GyverLibs** [comment]
Перезарядить не нужно, рефреш обновит интерфейс с учётом всех новых значений

**Comment by ghost** [comment]
у тебя так работает?
у меня в интерфейсе обновляется свич после перезахода

**Comment by ghost** [comment]
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/077f090c-043f-4e6f-9c41-3b85d3701c69)

**Comment by ghost** [comment]
а кстати что за tmr и GHtimer?
я его не удалял, но не знаю что это

**Comment by GyverLibs** [comment]
```cpp
bool s1, s2, s3;

void build() {
  hub.BeginWidgets();
  hub.WidgetSize(25);
  hub.Switch(&s1);
  hub.Switch(&s2);
  hub.Switch(&s3);
  if (hub.Button()) {
    s1 = 0;
    s2 = 0;
    s3 = 0;
    hub.refresh();
  }
}
```

**Comment by GyverLibs** [comment]
> что за tmr и GHtimer?

открыть [доку](https://github.com/GyverLibs/GyverHub/wiki#%D0%B2%D1%81%D0%BF%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D1%8B) и почитать

**Comment by ghost** [comment]
окей

**Comment by ghost** [comment]
> можно ли сделать так чтобы я вводил пароль, после этого можно было нажимать на SwitchIcon и чтобы я мог нажать кнопку заблокировать и у меня снова просило пароль перед нажатием

тогда можно сделать чтобы работало с помощью пароля, но я уже сделал hub.setPIN

**Comment by ghost** [comment]
а можно к тебе вопрос? не по гайверхабу но по твоему сайту, 
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/24530947-1eca-4aa4-89ee-1721271aeb24)
к какому пину подключать затвор мосфета и подойдет ли мосфет irf3205
это я к тому чтобы спросить, будет ли работать на esp8266

**Comment by GyverLibs** [comment]
Лучше взять мосфет с более низким уровнем открытия, в той же статье есть список. А ещё лучше взять драйвер, если подключать собрался мотор

**Comment by ultragamesik** [comment]
а драйверов на 40 ампер бывает? мне страшно брать на меньше, моя bms на 40A

**Comment by ghost** [comment]
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/07872a56-8281-42be-a945-75346252d0ad)
неф##а себе длинное название

**Comment by GyverLibs** [comment]
Мосфет сгорит на таком токе, тебе нужен драйвер для мотора, если это мотор, см урок по моторам там же

**Comment by ghost** [comment]
ну да мотор, 70 ампер с запасом, макс будет 40-60

**Comment by ghost** [comment]
esp8266 сможет управлять драйвером?

**Comment by GyverLibs** [comment]
К любому микроконтроллеру можно подключить драйвер

**Comment by ghost** [comment]
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/9f65cb62-0e7e-403c-a78b-b653221afab0)
или к компьютеру который будет идти на колесах за тобой?))))

**Comment by GyverLibs** [comment]
Это мусор, а не драйвер

**Comment by GyverLibs** [comment]
40-60 ампер в постоянном режиме это серьезный драйвер нужен. А что за моторы такие? Коллекторные на 70а

**Comment by ghost** [comment]
это в пике
а так 10-19а
ну у меня bms 3s40a отрубается от шуруповерта если в режиме сверления зажать патрон рукой

**Comment by ghost** [comment]
ну или это из за того что у меня на одной из трех банок (3s2p) вторая банка 18650 падает до 2.8 вольт а остольные норм

**Comment by GyverLibs** [comment]
Ну это жесть и довольно опасные эксперименты

**Comment by ghost** [comment]
у меня вторая банка старая ей 4 года... но этот же аккумулятор у меня в фонарике 100W из твоего видео и он работает
![viber_image_2023-09-03_19-40-07-926](https://github.com/GyverLibs/GyverHub/assets/95639806/7b85892b-6b94-4b4f-b62a-11fd5daddec8)

**Comment by ghost** [comment]
> Ну это жесть и довольно опасные эксперименты

ну да у меня там пару раз взрывался преоброзаватель и 1 раз аккумулятор и 1 раз светодиод незнаю из за чего сгорел

**Comment by ghost** [comment]
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/4bc6e04b-4d61-454e-96ed-88884a594d20)
1500 american dollars это много) и в Армению она придет через месяца 2-3

**Comment by ghost** [comment]
а из за чего мосфет сгорит? в даташите irf3205 написано макс ток 110 а

> Мосфет сгорит на таком токе, тебе нужен драйвер для мотора, если это мотор, см урок по моторам там же

**Comment by GyverLibs** [comment]
> 1500 american dollars

Не может этого быть. Он стоит 300 рублей, это 3-4 доллара. И американские доллары это USD, amd это армянский драм

> написано макс ток 110 а

Он вообще не откроется на 3.3 вольтах

**Comment by ghost** [comment]
ну ладно про доллары была шутка, а если модуль с мосфетом?

**Comment by GyverLibs** [comment]
Минимальное что может подойти - драйвер bts7960. И то его будет маловато, а мощнее вот так в продаже ничего нет, это надо самому собирать драйвер. А это силовая электроника и знаний нужно много. Про мосфеты забудь

**Comment by ghost** [comment]
а как работает кнопка с регулятором оборотов шуруповерта
я хочу такую же но с esp8266

**Comment by ghost** [comment]
забыл про транзисторы и мосфеты
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/bc4ba596-b293-4092-a022-386d984b43a0)

**Comment by GyverLibs** [comment]
Мосфет это и есть транзистор 🤷‍♂️

**Comment by ghost** [comment]
ну да только полевой
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/d66d5b9a-50ae-47c1-a1cc-0b3d35bafdd0)

**Comment by GyverLibs** [comment]
Кнопка шуруповерта - мосфет + драйвер мосфета. Скорее всего специальный ШИМ контроллер + драйвер в виде одной микросхемы

**Comment by ghost** [comment]
ну и что же ты предлагаешь делать? bts7960?

**Comment by GyverLibs** [comment]
Я ничего не предлагаю. Выше я написал - как минимум - драйвер bts7960. Либо проектировать/гуглить свою схему, взять хороший мосфет и драйвер для него. Возможно хватит эмиттерного повторителя. Это всё в гугл

**Comment by ghost** [comment]
мне дед тоже что то рассказовал про эмиттерный повторитель, пойду позвоню ему он скажет как что делать.

**Comment by ghost** [comment]
ладно, лень, буду делать через два шприца с водой))

**Comment by ghost** [comment]
а не подскажешь как включить реле на 5в от 3.3в?

**Comment by GyverLibs** [comment]
Какое реле? Что оно будет коммутировать?

**Comment by ghost** [comment]
модуль с реле, он не срабатовает с nodemcu v3 
он будет включать реле мощнее, уже на 70 ампер

**Comment by GyverLibs** [comment]
Всё там работает, питание реле на 5 вольт подключать надо

**Comment by ghost** [comment]
> Я ничего не предлагаю. Выше я написал - как минимум - драйвер bts7960. Либо проектировать/гуглить свою схему, взять хороший мосфет и драйвер для него. Возможно хватит эмиттерного повторителя. Это всё в гугл

а если подключить два драйвера параллельно?

**Comment by GyverLibs** [comment]
Не знаю, нужно читать изучать. Я не электронщик

**Comment by ghost** [comment]
А можно ли сделать так чтобы после нажатия на кнопку у меня открывалась страница ввода пин кода? hub.setPIN

**Comment by GyverLibs** [comment]
нет
