### ISSUE TITLE
HA Mqtt change status

### ISSUE THREAD

**Issue by tebenkov2222** [GyverLibs/GyverHub#25]
После отправки любых данных с Home assistant в esp статус в mqtt мгновенно меняется на offline. топик на получение доступности в HA я не вставлял по этому меняет статус только esp. Можете посмотреть данный момент?

**Comment by GyverLibs** [comment]
Сейчас клиент (приложение) полностью переписывается, возможно проблема решится сама собой после выхода крупного обновления

**Comment by tebenkov2222** [comment]
Приложением я пользуюсь только для проверки состояния (по крайней мере пока. позже вообще будет не нужно). Остальное планирую делать через умный дом по этому статус доступности хотелось бы тоже получать актуальный. Сейчас наверное сделаю костыль - обновлять статус каждую секунду. Но если после обновления все пофиксится то буде очень хорошо

**Comment by GyverLibs** [comment]
Тогда я не очень понял, где и после чего появляется offline? Я с HA не работал, не представляю что это такое даже

**Comment by tebenkov2222** [comment]
- Esp8266 (nodemcu3) подключен к локальному mosquitto (далее и до этого просто mqtt) вместе с HomeAsistant (далее и до этого просто HA), развернутых с помощью debian + docker.
- При подключении (перезагрузка или включение контроллера) к серверу mqtt он выставляет статус online. 
- При отправке данных с HA в mqtt в set топик (switch) статус контроллера сразу же меняется на offline
- контроллер данные принимает и отлично обрабатывает
- при всем этом, при дальнейших изменения данных топика контроллер их принимает и обрабатывает (а статус стоит offline)

**Comment by GyverLibs** [comment]
Возможно я не очень правильно понял как работает LWT топик, но делал как рекомендуют в интернете. Добавлю в список важных проблем, при случае разберусь
