### ISSUE TITLE
Не подключается устройство

### ISSUE THREAD

**Issue by ustav1982** [GyverLibs/GyverHub#26]
Стандартный пример **basic.ino**  прошивается и работает как положено.
Далее изменяю в нем стандартный блок команд для подключения к роутеру на создание точки доступа
```
  WiFi.mode(WIFI_AP);
  WiFi.softAP("AAAAAAAA", "12345678");
```

Подключаюсь к сети через Android-приложение.  Устройство уверенно находится в новой сети, но подключится к нему приложение не может. Красная строка ESP8266^Error, постоянно крутятся стрелки...

Есть какие то особенности работы через AP ?

**Comment by GyverLibs** [comment]
Неа, особенностей нет, у меня работает стабильно

**Comment by ustav1982** [comment]
С минимальным кодом отсюда
https://github.com/GyverLibs/GyverHub/wiki/2.-%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B#%D0%BC%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BE%D0%B4
ситуация аналогичная. 
Печаль.

**Comment by GyverLibs** [comment]
андроид приложение может некорректно работать на некоторых устройствах, к релизу возможно ситуация изменится

**Comment by ustav1982** [comment]
Вы правы.
Через скачанный GyverHub.html все работает через AP.

Потестировал немного. Подключение через AP на Андроид 9 не работает, на Андроид 10 и 12 работает.
В остальном пока на Андроид 9 ничего плохого не заметил.

**Comment by GyverLibs** [comment]
Можно установить PWA приложение с http версии сайта, оно отлично работает в режиме АР на всех андроидах, в Вики есть инструкция как это сделать

**Comment by ustav1982** [comment]
Мобильный Chrome при попытке открыть http сайт автоматически открывает его https версию. Проблема описана, и даже приводится ее решение, но я пока не смог побороть проблему. В целом все понятно.

**Comment by ustav1982** [comment]
Все понятно.
