### ISSUE TITLE
не работают обновления по воздуху

### ISSUE THREAD

**Issue by acup1** [GyverLibs/GyverHub#27]
я сохраняю бинарник из ide, а потом в меню приложения пытаюсь его залить, но по итогу он выдаёт ошибку(хоть и индицирует, что что-то качает)
![image](https://github.com/GyverLibs/GyverHub/assets/68469692/d0b5b26d-5b07-4872-8c08-51a222a0ce2f)
![image](https://github.com/GyverLibs/GyverHub/assets/68469692/3b04a664-11e1-4af2-98f1-8aa70624233c)

**Comment by GyverLibs** [comment]
микроконтроллер, плата, версия ядра?

**Comment by acup1** [comment]
> микроконтроллер, плата, версия ядра?

esp8266, LiLon NodeMCU V3, 3.0.1(если я правильно всё понимаю)

![image](https://github.com/GyverLibs/GyverHub/assets/68469692/f619f54f-0078-44d9-8bde-485727dd0101)

**Comment by GyverLibs** [comment]
странно, на 8266 отлично работало всё

**Comment by acup1** [comment]
> странно, на 8266 отлично работало всё

может я что-то не так делаю?

**Comment by GyverLibs** [comment]
не исключено

**Comment by acup1** [comment]
я просто сохраняю бинарный файл из ide и пытаюсь его залить, но что-то не работает

**Comment by acup1** [comment]
![image](https://github.com/GyverLibs/GyverHub/assets/68469692/e2298dc7-da2d-46d0-9d82-0864e87f8b71)
настройки для платы использую как по умолчанию

**Comment by acup1** [comment]
буквально сейчас затестил на wemos d1 mini и всё прекрасно работает, но всё же с nodemcu вопрос остаётся открытым

**Comment by acup1** [comment]
В таком случае могу предположить что проблема в ядре или в самой плате. Может ли такое быть что плата просто не может обновить прошивку на лету?

**Comment by GyverLibs** [comment]
Видимо ТС выбрал не ту плату. У ноды другие стоковые настройки, потому что другая память к ней припаяна
![image](https://github.com/GyverLibs/GyverHub/assets/84599917/47067265-b06e-4648-9c40-e32b369077a7)

**Comment by acup1** [comment]
не хочет шиться даже когда я выставил правильные настройки
![image](https://github.com/GyverLibs/GyverHub/assets/68469692/037fdd7e-3197-49ad-a1eb-5691c1ea80b3)
