### ISSUE TITLE
При иминении в config.hpp GH_FS на другой FS в utils\misc.h он не менняется и остается LittleFS 

### ISSUE THREAD

**Issue by DenysChuhlib** [GyverLibs/GyverHub#28]
Здраствуйте. С этой проблемой не получается поменять GH_FS на что-то другое.

**Comment by DenysChuhlib** [comment]
И utils\misc.h невидит не только параметры с config.hpp, а и со скетча, и другие библиотеки для FS не подлючаются, но так как там всегда LittleFS то компилятор не видит ошибки.

**Comment by GyverLibs** [comment]
никогда такого не было и вот опять

**Comment by DenysChuhlib** [comment]
Для замены FS на SD, не получается по нескольким причинам

1.  для старта используется `GH_FS.begin(true);` и для ESP32 это визовет ошибку компиляции так как `begin` там другой.
2.  в ESP32 в SD `totalBytes()` `usedBytes()` очень надолго торозят плату при их вызове (я делал костыль ещё с порталом)
3. в esp8266 для SD нужно использовать `info64()` для получения полного и коректного розмера картки

> PS : Вопще FS  на ESP32  такое не удобное по сровнению с esp8266

**Comment by GyverLibs** [comment]
Всего 3 варианта файловой системы может быть? Spiffs/littlefs/sd_fs? Можно добавить "правильно" sd_fs в библиотеку. Вообще очень жалко что индусы не сделали нормально файловые системы, чтобы они были совместимы друг с другом на обеих платформах

**Comment by DenysChuhlib** [comment]
> Всего 3 варианта файловой системы может быть?

Да, но я сделал для себя билбу которая их може все объеденить в 1, просто выртуальные папки показывают диски и в них файлы лежат и загружатся файлы. (проверял показ с littlefs на esp8266 )

**Comment by DenysChuhlib** [comment]
По этому, и всплыли нюансы

**Comment by DenysChuhlib** [comment]
Ну эти путнкты можна решить:

1.  Убрать `begin` FS с `begin` хаба и оставеть его юзерам
2. сложно (могу пояснить костыль, но это костыль)
3. просто сменить функцию на info64

**Comment by GyverLibs** [comment]
достаточно так же как сейчас добавить отдельный вариант для SD_FS

**Comment by GyverLibs** [comment]
у 8266 нужно указать SS, а у 32 просто begin() верно?

**Comment by DenysChuhlib** [comment]
> достаточно так же как сейчас добавить отдельный вариант для SD_FS

Ну да, и сделайте чтобы можно оключить, для запуска з другими настройками. (и что бы я мог запустить свою)

**Comment by DenysChuhlib** [comment]
> у 8266 нужно указать SS, а у 32 просто begin() верно?

наоборот

**Comment by GyverLibs** [comment]
* [esp8266](https://github.com/esp8266/Arduino/blob/1662248b394740d82824f504a021d4dad3d314b6/libraries/SD/examples/listfiles/listfiles.ino#L35)
* [esp32](https://github.com/espressif/arduino-esp32/blob/1f1a9ae4b58c27e3af059eb3a8832aa6132872f6/libraries/SD/examples/SD_Test/SD_Test.ino#L219C18-L219C18)

**Comment by DenysChuhlib** [comment]
ааа

**Comment by DenysChuhlib** [comment]
на esp8266 два SD

**Comment by DenysChuhlib** [comment]
просто SD для совместимости и он сделан на SDFS

**Comment by GyverLibs** [comment]
ужяс

**Comment by DenysChuhlib** [comment]
лутше SD уже в ручну все будут

**Comment by DenysChuhlib** [comment]
Я подправил сообщения
> Для замены FS на SD, не получается по нескольким причинам
> 
> 1. для старта используется `GH_FS.begin(true);` и для ESP32 это визовет ошибку компиляции так как `begin` там другой.
> 2. в ESP32 в SD `totalBytes()` `usedBytes()` очень надолго торозят плату при их вызове (я делал костыль ещё с порталом)
> 3. в esp8266 для SD нужно использовать `info64()` для получения полного и коректного розмера картки

> Ну эти путнкты можна решить:
> 
> 1. Убрать `begin` FS с `begin` хаба и оставеть его юзерам
> 2. сложно (могу пояснить костыль, но это костыль)
> 3. просто сменить функцию на info64

**Comment by DenysChuhlib** [comment]
У меня появились идеи для FS

1.  сделать клас `HubFS` (не от класа `FS`, а просто клас) для реализации всех нюансов FS, внутри используя GH_FS, с такими функциям:

- `openRead(CSTR path)`
- `openWrite(CSTR path)`
- `open(CSTR path, char mode)`
- `opneHTTP()` - для папки с доступом по HTTP
- `uint64_t totalBytes()` для ESP32 такие самые а для 8266 чере функцию `info64()`
- `uint64_t usedBytes()`
- `format()`
- `openReadIndex()`, `openReadScript()`, `openReadStyle()` и добавить в конфиг путь где они находятся, и этим конфигом менят уже в этих функция.
- `begin()` + конфиг на отключения / ручной `begin`
- `end()`
- `openWeb()` - это функция к второй идеи
И спользоват этот клас заместь кучи кусков проверок какая это плата и какой фс.

2. Это сделать возможним загрузки полной версии сайта с SD картки. Таким образом мы не терям функционал и удобства.

**Comment by GyverLibs** [comment]
Я сейчас переписываю библиотеку и тоже к этому пришёл

Мне кажется в sd карте нет смысла. Гораздо проще и лучше использовать еспшки с увеличенным количеством flash, там до 16мб есть вемосы даже. А полная версия сайта весит около 300кб в зипе, из которых 250 это бесполезный для есп версии mqtt

**Comment by DenysChuhlib** [comment]
> Мне кажется в sd карте нет смысла.

Кождый сам найдет преминение. Например мне продругому никак уже. Плату менять слишком геморно. Да и памяти на влешке навалом. Лишним не будет.

**Comment by DenysChuhlib** [comment]
> лучше использовать еспшки с увеличенным количеством flash

И если можно будет с SD, то можно будет использоват любые платы с Ethernet модулями. (не только esp)

**Comment by GyverLibs** [comment]
Сейчас тоже можно использовать с ethernet. Но библиотечный FS и http к этому отношения не имеет. Юзер у себя в программе должен сам реализовать связь и сам отправить файлы сайта с карты памяти с учётом особенностей платформы. Внутри библиотеки это сделать не получится

**Comment by DenysChuhlib** [comment]
Понятно
