### ISSUE TITLE
в FastLed и GyverHub есть переменная или что это, называються colors выдаёт ошибку вроде из за того что их 2 а название одно и тоже

### ISSUE THREAD

**Issue by ghost** [GyverLibs/GyverHub#30]
` In file included from c:\Users\User\Documents\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from C:\Users\User\Documents\Arduino\sketch_oct12a\sketch_oct12a.ino:26:
c:\Users\User\Documents\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  157 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\User\Documents\Arduino\sketch_oct12a\sketch_oct12a.ino: In function 'void setup()':
C:\Users\User\Documents\Arduino\sketch_oct12a\sketch_oct12a.ino:129:3: error: 'dlog' was not declared in this scope; did you mean 'log'?
  129 |   dlog.begin();           // лог тоже запустить
      |   ^~~~
      |   log
C:\Users\User\Documents\Arduino\sketch_oct12a\sketch_oct12a.ino: In function 'void drawRainbow(int)':
C:\Users\User\Documents\Arduino\sketch_oct12a\sketch_oct12a.ino:165:20: error: 'colors' was not declared in this scope; did you mean 'GHcolors'?
  165 |     leds[i] = CRGB(colors[index][0], colors[index][1], colors[index][2]);
      |                    ^~~~~~
      |                    GHcolors
In file included from c:\Users\User\Documents\Arduino\libraries\FastLED\src/FastLED.h:58,
                 from C:\Users\User\Documents\Arduino\sketch_oct12a\sketch_oct12a.ino:26:
c:\Users\User\Documents\Arduino\libraries\FastLED\src/fastpin.h: In instantiation of 'class FastPin<6>':
c:\Users\User\Documents\Arduino\libraries\FastLED\src/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<6, 20, 50, 30, GRB, 0, false, 85>'
c:\Users\User\Documents\Arduino\libraries\FastLED\src/chipsets.h:654:7:   required from 'class WS2812Controller800Khz<6, GRB>'
c:\Users\User\Documents\Arduino\libraries\FastLED\src/FastLED.h:132:52:   required from 'class WS2812B<6, GRB>'
c:\Users\User\Documents\Arduino\libraries\FastLED\src/FastLED.h:352:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 6; EOrder RGB_ORDER = GRB]'
C:\Users\User\Documents\Arduino\sketch_oct12a\sketch_oct12a.ino:67:66:   required from here
c:\Users\User\Documents\Arduino\libraries\FastLED\src/fastpin.h:261:24: error: static assertion failed: Invalid pin specified
  261 |  static_assert(validpin(), "Invalid pin specified");
      |                ~~~~~~~~^~

exit status 1

Compilation error: 'dlog' was not declared in this scope; did you mean 'log'? `

**Comment by ultragamesik** [comment]
не отправляеться код в виде кода...

**Comment by ghost** [comment]
и на dlog жалуеться что его нет

**Comment by GyverLibs** [comment]
99% ошибка в скетче. Потому что программу нужно писать постепенно и проверяя новое добавленное, а не всю сразу. Если не получится - прикрепи свой скетч

**Comment by ghost** [comment]
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/320a55a1-d175-4385-8eed-a6652293da38)

**Comment by ghost** [comment]
Убрал всё, чего нету в GyverHub, но ошибка dlog осталась.

**Comment by GyverLibs** [comment]
ну так удали его, зачем тебе запускать лог которого не существует? Я так понимаю взял пример full demo где лог есть, всё удалил, а лог оставил. Начинать работу нужно с примера basic и чтения документации, а не наваливать всё в кучу не зная ничего
