### ISSUE TITLE
считаю полезным и важным функционал загрузки файла по <form> html

### ISSUE THREAD

**Issue by 4tr** [GyverLibs/GyverHub#31]
всякие приложения и утилиты загрузки файлов в SPIFSS в самый неподхлдящий момент могут не оказаться под рукой, и МК может оказаться почищен. именно для этого я в своих поделках оставлял алгоритм проверяющий есть ли index.html  если его нет то в корне грузистся страничка простейшей загрузки файлов корорая без стилей и JS выполняет первичные обязанности вдохнуть жизнь в устройство через любой доисторический девайс умеющий в сеть или wifi.

**Comment by GyverLibs** [comment]
Загрузить файл в пустой МК можно через менеджер файлов в приложении, городить какие то свистопляски не имеет смысла

**Comment by 4tr** [comment]
> Загрузить файл в пустой МК можно через менеджер файлов в приложении, городить какие то свистопляски не имеет смысла

прошу понять, очень даже имеют смысл, пересмотрите решение. 
Главное это вообще не сложно внедрить. это сильно расширит вариативность и отказоустойчивость.  Да я вижу надстройку GH_INCLUDE_PORTAL, но это не всегда позволительно в случае с видео на ESP32 .  я без на данной функции загрузки много сил потерял, потом ее реализовал и горя не знаю.  решил переносить свои проекты на ваш хаб. а там отказоустойчивость критична. 
 
этот загрузчик на комп не всегдаудается поставить (не забываем про кросплатформерность итд), как выясняется.  я к примеру на этом попался, десятки инструкций перелопатил и все они не подошли. я не могу себе позволить все удалить под чистую, помрут многие проекты.   я лишь уточнил что это довольно важно и позволит не окирпичивать устройство по банальному.  даст возможность легкого старта с вариантами НЕ зависящими от ПО машины.   Про приложение, это надо иметь приложение, а зачем если у мк есть вебсервер в котором нужна всего одна строчка html кода в виде <body><form method="POST" action="/upload" enctype="multipart/form-data"><input type="file" name="upload">
<input type="submit" name="file"><form></body>

**Comment by GyverLibs** [comment]
Я всё ещё не понял что требуется. Загружать файлы можно через сайт-приложение, всё отлично работает. Утилиты для компьютера никакие устанавливать не нужно

**Comment by 4tr** [comment]
> Я всё ещё не понял что требуется. Загружать файлы можно через сайт-приложение, всё отлично работает. Утилиты для компьютера никакие устанавливать не нужно

значит у меня оно не запустилось.  если загрузить голый скетч и зайти по IP мне никто не предлагает загрузить файлы.    работать начинает только если прошить из в облать флеша GH_INCLUDE_PORTAL.  но это не всегда допустимо и есть вопросы как это обойти.    ну либо я пока не нашел инструкцию в которой что-то пишется по этому поводу.

**Comment by 4tr** [comment]
если я не использую "GH_INCLUDE_PORTAL"  ожидаемое поведение на каптив портале это редирект на страницу загрузки  поле с выбором файла и кнопка "загрузить". вот что я имел ввиду.   прошить ведь и бинарник можно в голую ESP когда вообще никаких IDE под рукой нет.    надеюсь на понимание.   Если эта загрузка есть, то, возможно она где-то далековато.

**Comment by 4tr** [comment]
> Я всё ещё не понял что требуется. Загружать файлы можно через сайт-приложение, всё отлично работает. Утилиты для компьютера никакие устанавливать не нужно

или ты имеешь ввиду что можно просто открыть в браузере локально оболочку чтобы её-же и зарузить? уже решение, но может не везде заработать.  я тут занимаюсь некродевайсами и на них работает только старый HTML без JS и открыть новомодный дизайн уже не удастся вообще никак, а вот загрузить файлы захочется.  ну я тебя примерно понял,  изучу этот вариант как время будет.

**Comment by GyverLibs** [comment]
понял, добавить страничку загрузки, чтобы загрузить файлы приложения. Сделаю, в ближайшем обновлении появится. Также без поддержки JS хаб работать не будет, там абсолютно всё сделано на JS, даже подгрузка и рендер главной страницы

**Comment by 4tr** [comment]
> понял, добавить страничку загрузки, чтобы загрузить файлы приложения. Сделаю, в ближайшем обновлении появится. Также без поддержки JS хаб работать не будет, там абсолютно всё сделано на JS, даже подгрузка и рендер главной страницы

про JS я это ночью изучил, до чего добрался.  я не люблю (ненавижу) когда JS перегружают, но понимаю что тут на этом весь дизайн держится и он уместен, однако хотелось бы добавить как можно безболезненный вход в первичную настройку.  я пока намерен присоединиться к вам и превносить подобные решения (работы древних устройств с хабом)  дабы хаб был максимально гибок.    мне надоело собственные каптивы и оболочки в одно жало писать, лучше подстроиться под вашу систему, вот критичные для меня вещи, на которых шишки набил и пишу (пока эта вещь одна, остальное просто шикарно). перенесу пару проектов на ваш хаб, какраз будет время изучить тонкости (один проект с ЛБП другой с панелью управления на 66 кнопок)

**Comment by GyverLibs** [comment]
сейчас пока что лучше не переносить, планируется крупное обновление где всё будет по другому, а приложение и библиотека полностью переписаны

**Comment by 4tr** [comment]
> сейчас пока что лучше не переносить, планируется крупное обновление где всё будет по другому, а приложение и библиотека полностью переписаны

это плохо.  за много лет только шишка встала полечить их болячки... я тогла не смог на сокете нормально запуститься, пришлось простыми тяжелыми пачками кидаться.  где-то можно увидеть эти изменения? я пока только мастер ветку вижу в гите, ты на локалке видимо все пилишь. просто есть сразу с ходу вопросы по маштабируемости и применимости к проектам.   Я прекрасно понимаю что тебе не до этого чтобы болтать со мной, но может смогу привнести полезное.  Приложение меня не интересует пока вообще, я сейчас смотрю истключительно на девайс как самостоятеллное устройство "эдакий сервер"  и еще один такой сервер как головное устройство, но при этом они не особо зависят друг от друга и могут сами по себе.

**Comment by GyverLibs** [comment]
почему же плохо, проект очень сильно улучшается и развивается. Изменения библиотеки сейчас только локально, приложение - вот тут https://github.com/GyverLibs/GyverHub-web

**Comment by 4tr** [comment]
прошу прощения, я не это имел ввиду.  я в том, что не рекомендуете что-то писать на этой версии.  а то,что она обновляется разумеется хорошо.  главное чтобы текущий подход к универсальности сохранился.

**Comment by GyverLibs** [comment]
универсальность как раз увеличится)

**Comment by 4tr** [comment]
ну и отлично.  я на своем недоделанном проекте планировал чтобы прошивка была одна, а все накладные функции (не уникальные)  добавлялись конфигурацией и динамически инициализировались на лету, тогда (если в двух словах)  можно чуть ли не свой ресурс конфигураций подымать для решения типовых задач ( всякие погодные станции и логика отработки условий)  в своих поделиях (не доделал правда) реализовал аналог задачника crone* только с точностью в секунды. грузишь конфигурацию типа 
> 0 0 0 1 1 1 "с новым годом"    именно по этому мне было важно иметь загрузку работающую на любом(вообще любом) устройсве.

**Comment by 4tr** [comment]
у тебя так и вовсе все на JS генерится, что мешает минимизировать участие прошивки в конфигурации. т.е. сама прошивка может впринципе никак не модифицироваться от проекта к проекту, тольок файлы конфигов меняются.  МК лишь нужно заниматься транзитом данных исходя из конфигов (элементарная проверка на адекватность запроса)
