### ISSUE TITLE
режим AP [мелочи]

### ISSUE THREAD

**Issue by 4tr** [GyverLibs/GyverHub#32]
в режиме  WIFI_AP неадекватно отображается SSID. По факту берется когда объявляется GyverHub hub("хх","yy","$);  а в info выдает значение которое было ранее в режиме WIFI_STA

**Comment by GyverLibs** [comment]
Почему неадекватно, ssid это и есть имя точки доступа из WiFi.SSID(). Даже если сейчас режим другой, имя точки есп запомнила

**Comment by 4tr** [comment]
> Почему неадекватно, ssid это и есть имя точки доступа из WiFi.SSID(). Даже если сейчас режим другой, имя точки есп запомнила 

я про то, что в режиме AP она подымает с именем "хх"  а в info пишет другое.  или SSID это только имя точки в режиме AP?   это то-же что и из разных мест кода брать IP в этих двух режимах.  Тут я пологаю либо нужно добавить еще одно поле в котором он фактическое имя даст, либо не путать людей , ведь не только программисты знающие особенности ESP будут этим пользоваться.   (я сугубо для пользы дела, мне самому это не особо мешает)

**Comment by GyverLibs** [comment]
В SDK есть недокументированная функция для получения имени именно soft ap. Я добавлю в инфо, спасибо за идею

**Comment by GyverLibs** [comment]
Прямо вот так и сделаю тогда
![image](https://github.com/GyverLibs/GyverHub/assets/84599917/e9bfbb23-faf5-4451-8f5a-299e8d6ba757)
