### ISSUE TITLE
работа c URL [отклонено]

### ISSUE THREAD

**Issue by 4tr** [GyverLibs/GyverHub#33]
изучая хаб сначала чуствовал неудобство по части юзабилити, потом вник в то что мешало и обратил внимание на важную проблему (я так считаю)  необходима адекватная работа с урлами например вот так: 
'192.168.4.1/info'
или
'192.168.4.1?page=config'

только ни в коем случае не так (извините не удержался, уж больно мого якорных костылингов насмотрелся, когда они могут нативно работать  )
'192.168.4.1#freaklinks'

дело в том, что каждое обновление страницы скидывает меня на страницу поиска что никак не является юзабельным решением.  При попытке что-то ввести, это что-то игнорится* . Ну разумеется я не вижу смены URL при скитании по интерфейсу. 
я понимаю, что урл может содержать в себе что-то типа devId для адекватного взаимодействия., не говоря уже о списке виджетов и варианту оформления (для интеграции в другие системы "как есть")

если что-то описал не так, прошу прощения, я только изучаю систему.

**Comment by GyverLibs** [comment]
Хаб - исключительно однстраничное приложение, я думаю по очевидным причинам. И не нужно плодить issue - пока мы в бета версии - всё обсуждается в одном общем issue, особенно такие мелкие вопросы

**Comment by 4tr** [comment]
> Хаб - исключительно однстраничное приложение, я думаю по очевидным причинам. И не нужно плодить issue - пока мы в бета версии - всё обсуждается в одном общем issue, особенно такие мелкие вопросы

данный вопрос мне не показался мелким, крайне важная штука на мой взгляд.  под понятие "одностраничный" легко подпадает вид линков 
'192.168.4.1?page=config' 
по сути это одна страница с уточняющими параметрами.   
поверь, проекты которые я хотел перенести на этот хаб вот конкретно к этой особенности работы сверх критичны. 

спасибо за уточнения порядка написания сообщений, буду дальше туда писать.

**Comment by GyverLibs** [comment]
такой возможности не будет, потому что прежде чем открыть инфо, нужно обнаружить устройство по всем доступным каналам связи, соединиться с ним и запросить инфо. И это только одна из причин

**Comment by 4tr** [comment]
я пока писал первое сообщение , хотел, но забыл указать, что я работаю с устройствами в локалке. т.е. по ip открываю в браузере  приложение непосредственно с той ESP с которой я хочу общаться в данный момент и она как-бы обязана* быть.  
я не хочу показаться навящивым или неадекватным, но видимо вы недооценииваете проблему.   Я понимаю что должны произойти какие-то приготовления в коде, но конечному пользователю о этом знать и не надо. Если ему на экране нужно видеть температуру и влажность, как вы объясните то, что для этого ему  нужно каждый раз прокликивать менюшки.окошки. приложения , когда можно было этого вовсе не делать.   

следовательно если вы все-же не будете идти в этом направлении придется изучить тему и сделать эту поддержку самому, ну либо опять через боль и страдания писать собственные костыли. =(    я бы с удовольствием пообщался с вами на эту тему (не в ущерб ни вашему ни своему времени) предложение направил на электронную почту "для комерческих предложений".    Лично я писал много костылей и говнокода, не рад этому сам, лучше продвинуть и расширить вашу систему если идеи идеологически это не будут противоречить друг другу.

**Comment by 4tr** [comment]
в общем касательно этой функции готов подискутировать и доказать что это реально важная штука (на реальных примерах проектов а не абстрактных обсуждениях)  если вы готовы общаться на эту тему ( я прекрасно понимаю что вы мне ничем не обязаны и по этому в таком тоне пытаюсь общаться)

**Comment by GyverLibs** [comment]
такой фичи в официальной версии не будет. Не только потому что это бесполезно, но и по техническим причинам

**Comment by 4tr** [comment]
это не бесполезно. создавая страницу  на JS вы просто этим пренебрегли не понимая на сколько это важно.  Писал выше что уже сейчас это критично важно для моих (уже сделанных) проектов.

 вообще в веб проектах работа с урл это как само по себе очевидное явление и именно кастрация этого функционала должна быть обоснована какими-то серьезными основаниями, но никак не на оборот.

 ясно, значит буду пилить её сам. а там со временем станет понятно о чем я говорил. вообще никаких технических причин "сэмулировать" один-два кливка быть не должно. а когда страница грузится с самой есп, пологаю должен быть принудительный режим поиска "самой себя"  дабы не надо было что-то обновлять.   апендицит тоже долгое время считали бесполезным... пока не дошло зачем он в организме.  вот такой подход JS  разработчиков меня и бесит, делают красивые свистоперделки тяжелыми алгоритмами, а функции и возможности уничтоженные этими свистоперделками годами нарабатываемые стандартами HTML и CSS идут лесом, в итоге получаются новые,крутые, красивы и невообразимо идиотско работающие устройства с килотонной зависимостей и ни дай бог хоть одно условие не пройдёт...

**Comment by 4tr** [comment]
пологаю под "техническими причинами"  вы имели ввиду невозможность такого кода?
`const urlParams = new URLSearchParams(window.location.search);
	if (urlParams.get('id') != null){
	refresh_h(); setTimeout(() => {
		device_h(urlParams.get('id'));
	}, "2000");
}`
у меня заработало прекрасно, и сразу меньше проблем стало

**Comment by GyverLibs** [comment]
Данный проект - изначального не сайт, а приложение. Если такая парадигма не устраивает - не пользуйтесь. Но и писать чушь про "свистоперделки" и "стандарты html" тоже пожалуйста не нужно.

> вы имели ввиду невозможность такого кода

Где я писал что невозможно? Я писал что такого функционала не будет

**Comment by 4tr** [comment]
я не пытаюсь оскорбить, просто для меня это очевидно, и не знаю как довести это до вас.  Пока я принял решение сделать форк и там все необходимое писать. если сил хватит буду дополнять библиотеку важными для меня решениями самостоятельно.

**Comment by 4tr** [comment]
я бы с удовольствием поработал на общее благо, но видимо то что для меня важно вам вообще не интересно.  ну так и быть, мне может даже легче будет. можно не вылизывать код до идеала в своей версии.
