### ISSUE TITLE
мелкие правки интерфейса [не критично] [мелкие правки]

### ISSUE THREAD

**Issue by 4tr** [GyverLibs/GyverHub#34]
с кодом пока не осваивался по этому пока словесно опишу. компилировал скетч с параметрами 

`#define GH_INCLUDE_PORTAL // включить сайт в память программы (не нужно загружать файлы в память)`
`#define GH_NO_MQTT      // off MQTT`
`#define GH_NO_OTA       // off ОТА файлом с приложения`
`#define GH_NO_OTA_URL   // off ОТА по URL`

однако в меню "info" веб версии меня сбило с толку поле с "урлами" как мне по началу показалось, немного выбесило что я не могу чать урла скопировать, потом выяснилось что это вовсе не урлы а топики для MQTT который я изначально вроде как отрезал.   одижаемое поведение либо надпись о отключенной поддержке MQTT либо вовсе отсутствие данного поля (Topics).

На странице работы с файлами остались заголовки 
`OTA FILE`
`OTA URL`

**Comment by GyverLibs** [comment]
Всё верно. Информация об устройстве остаётся в любом случае. А блоки ота скрываются, остаются только заголовки

**Comment by 4tr** [comment]
пишу сюда а не в обший топик, чтобы не пупать переписку. в дальнейшем  по другим вопросам буду писать туда.


т.е  поддержка на уровне железа MQTT вроде как отключена,  а информация для связи имеется (выходит запутывание)

**Comment by GyverLibs** [comment]
ок, уберу в обновлении, если смущает
