### ISSUE TITLE
GSM модуль

### ISSUE THREAD

**Issue by ghost** [GyverLibs/GyverHub#36]
Здравствуйте! Можно ли использовать GSM модуль с SIM-картой для доступа к MQTT серверу?
Если никак, прошу добавить такую функцию в следущих обновлениях.

**Comment by GyverLibs** [comment]
Можно использовать любой способ связи, хоть голубиной почтой. Но нужно реализовать его самостоятельно и подключить в библиотеке в ручной режим, в документации вроде бы описано

**Comment by ghost** [comment]
Можно ссылку на документацию? На ту страницу, где это описано как делать.

**Comment by GyverLibs** [comment]
пока всё что есть - [самая последняя глава](https://github.com/GyverLibs/GyverHub/wiki/8.-%D0%A0%D1%83%D1%87%D0%BD%D0%BE%D0%B9-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC) про ручной режим
