### ISSUE TITLE
Dpad

### ISSUE THREAD

**Issue by ghost** [GyverLibs/GyverHub#37]
Dpad - 4-х кнопочный виджет.
А почему в Dpad пишут GH.pos, pos это же позиция x,y.
Можно узнать на какую кнопку нажали?
![image](https://github.com/GyverLibs/GyverHub/assets/95639806/a890de9e-0efb-4d6c-9f77-6ca6fb660bc1)

**Comment by GyverLibs** [comment]
в случае с дипадом pos принимает значения по осям `1` и `-1`
