### ISSUE TITLE
Работа с документацией

### ISSUE THREAD

**Issue by maleksware** [GyverLibs/GyverHub#4]
Актуальны ли сейчас пулл-реквесты в документацию, например, перевод и мелкие правки? Заметил, что Гугл не переводит комментарии в сниппетах, возможно, стоит рассмотреть вариант ручного перевода, да и в локали у разрабов за бугром будет дока, которую они могут без перевода читать.

**Comment by GyverLibs** [comment]
Не актуальны до релиза
