### ISSUE TITLE
Ошибка компиляции Lolin Wemos D1 R2 & mini

### ISSUE THREAD

**Issue by Dibuk1234** [GyverLibs/GyverHub#42]
Взял пример кода из документации хотел пощупать что это вообще такое а тут это.

Arduino: 1.8.19 (Windows 10), Плата:"LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Disabled, 4M (3M SPIFFS), v2 Lower Memory, Disabled, None, All Flash Contents, 115200"

In file included from C:\Program Files (x86)\Arduino\libraries\GyverHub-main\src/canvas.h:10:0,

                 from C:\Program Files (x86)\Arduino\libraries\GyverHub-main\src/builder.h:4,

                 from C:\Program Files (x86)\Arduino\libraries\GyverHub-main\src/GyverHub.h:6,

                 from C:\Users\dbura\OneDrive\Документы\Arduino\ArduboyHub\ArduboyHub.ino:2:

C:\Program Files (x86)\Arduino\libraries\GyverHub-main\src/utils/misc.h:12:22: fatal error: LittleFS.h: No such file or directory

 #include <LittleFS.h>

                      ^

compilation terminated.

exit status 1

Ошибка компиляции для платы LOLIN(WEMOS) D1 R2 & mini.

**Comment by GyverLibs** [comment]
[в самом начале документации](https://github.com/GyverLibs/GyverHub/wiki/2.-Начало-работы#esp8266esp32) написано о минимальной версии ядра для работы библиотеки
