### ISSUE TITLE
Что-то не работает. код правильный

### ISSUE THREAD

**Issue by IlyaDudelzak** [GyverLibs/GyverHub#46]
код:
`#include <Arduino.h>

#define AP_SSID "Welcome"
#define AP_PASS "WLC202!d"

#include <GyverHub.h>
GyverHub hub;

#include <PairsFile.h>
PairsFile data(&GH_FS, "/data.dat", 3000);

#include <WS2812FX.h>`
вкладка builder
`// билдер
void build(gh::Builder& b) {
  b.Label().value("Гирлянда");
  {
    gh::Row r(b);
    b.Switch_("power", &data).label("Питание").size(25);
    b.Slider_("Brightness", &data).label("Яркость").size(75);
  }
  {
    gh::Row r(b);
    b.Select_("ledType", &data).text("GRB;RGB;RGBW");
    b.Spinner_("ledAmount", &data).label("Кол-во светодиодов");
  }
  b.Slider_("speed", &data).label("Скорость эффекта");
}`
вкладка effects
`void rgbTick(){
  
}`
вкладка setuploop
`void setup() {
    Serial.begin(115200);

#ifdef GH_ESP_BUILD
    // подключение к роутеру
    WiFi.mode(WIFI_STA);
    WiFi.begin(AP_SSID, AP_PASS);
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }
    Serial.println();
    Serial.println(WiFi.localIP());

    hub.mqtt.config("test.mosquitto.org", 1883);  // + MQTT

    // ИЛИ

    // режим точки доступа
    //WiFi.mode(WIFI_AP);
    //WiFi.softAP("My Hub");
    //Serial.println(WiFi.softAPIP());
#endif

    hub.config(F("EspIlyaDevices"), F("ESP"));
    hub.onBuild(build);
    hub.begin();
    data.begin();
    hub.onUpload([](String& path) {
        Serial.print("Uploaded: ");
        Serial.println(path);
        if (path == "/data.dat") data.begin();  // refresh from file
    });
}

void loop() {
  data.tick();
  hub.tick();
  rgbTick();
}`

Ошибка непонятная:
`Компиляция скетча...
"C:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\python3\\3.7.2-post1/python3" -I "C:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2/tools/signing.py" --mode header --publickey "D:\\Disk-U\\Ilya\\Documents\\Arduino\\girlanda/public.key" --out "C:\\Users\\Ilya\\AppData\\Local\\Temp\\1\\arduino_build_34379/core/Updater_Signing.h"
"C:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\3.1.0-gcc10.3-e5f9fec/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE -DESP8266 "@C:\\Users\\Ilya\\AppData\\Local\\Temp\\1\\arduino_build_34379/core/build.opt" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2/tools/sdk/include" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2/tools/sdk/lwip2/include" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\Ilya\\AppData\\Local\\Temp\\1\\arduino_build_34379/core" -c "@C:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2/tools/warnings/extra-cppflags" -Os -g -free -fipa-pta -Werror=return-type -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -MMD -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10813 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_WEMOS_D1MINI\"" "-DARDUINO_BOARD_ID=\"d1_mini\"" -DFLASHMODE_DIO "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\cores\\esp8266" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\variants\\d1_mini" "-ID:\\Disk-U\\Ilya\\Documents\\Arduino\\libraries\\GyverHub\\src" "-ID:\\Disk-U\\Ilya\\Documents\\Arduino\\libraries\\StringUtils\\src" "-ID:\\Disk-U\\Ilya\\Documents\\Arduino\\libraries\\Pairs\\src" "-ID:\\Disk-U\\Ilya\\Documents\\Arduino\\libraries\\GSON\\src" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\libraries\\LittleFS\\src" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\libraries\\ESP8266WiFi\\src" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\libraries\\ESP8266HTTPClient\\src" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\libraries\\ESP8266httpUpdate\\src" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\libraries\\ESP8266WebServer\\src" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\libraries\\DNSServer\\src" "-ID:\\Disk-U\\Ilya\\Documents\\Arduino\\libraries\\PubSubClient\\src" "-ID:\\Disk-U\\Ilya\\Documents\\Arduino\\libraries\\arduinoWebSockets\\src" "-ID:\\Disk-U\\Ilya\\Documents\\Arduino\\libraries\\WS2812FX\\src" "-ID:\\Disk-U\\Ilya\\Documents\\Arduino\\libraries\\Adafruit_NeoPixel" "-IC:\\Users\\Ilya\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.1.2\\libraries\\Hash\\src" "C:\\Users\\Ilya\\AppData\\Local\\Temp\\1\\arduino_build_34379\\sketch\\girlanda.ino.cpp" -o "C:\\Users\\Ilya\\AppData\\Local\\Temp\\1\\arduino_build_34379\\sketch\\girlanda.ino.cpp.o"
C:\Users\Ilya\AppData\Local\Temp\1\arduino_build_34379\sketch\girlanda.ino.cpp:1:1: error: stray '##' in program
    1 | ##line 2 "D:\\Disk-U\\Ilya\\Documents\\Arduino\\girlanda\\builder.ino"
      | ^~
C:\Users\Ilya\AppData\Local\Temp\1\arduino_build_34379\sketch\girlanda.ino.cpp:1:3: error: 'line' does not name a type
    1 | ##line 2 "D:\\Disk-U\\Ilya\\Documents\\Arduino\\girlanda\\builder.ino"
      |   ^~~~
D:\Disk-U\Ilya\Documents\Arduino\girlanda\builder.ino: error: 'line' does not name a type
In file included from c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\utility:76,
                 from c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\algorithm:60,
                 from C:\Users\Ilya\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\cores\esp8266/Arduino.h:229,
                 from D:\Disk-U\Ilya\Documents\Arduino\girlanda\builder.ino:1:
c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\initializer_list:53:15: error: 'size_t' does not name a type
   53 |       typedef size_t   size_type;
      |               ^~~~~~
In file included from c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\utility:76,
                 from c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\algorithm:60,
                 from C:\Users\Ilya\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\cores\esp8266/Arduino.h:229,
                 from D:\Disk-U\Ilya\Documents\Arduino\girlanda\builder.ino:1:
c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\initializer_list:1:1: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
  +++ |+#include <cstddef>
    1 | // std::initializer_list support -*- C++ -*-
In file included from c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\utility:76,
                 from c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\algorithm:60,
                 from C:\Users\Ilya\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\cores\esp8266/Arduino.h:229,
                 from D:\Disk-U\Ilya\Documents\Arduino\girlanda\builder.ino:1:
c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\initializer_list:59:7: error: 'size_type' does not name a type
   59 |       size_type   _M_len;
      |       ^~~~~~~~~
c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\initializer_list:62:54: error: 'size_type' has not been declared
   62 |       constexpr initializer_list(const_iterator __a, size_type __l)
      |                                                      ^~~~~~~~~
c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\initializer_list:70:17: error: 'size_type' does not name a type
   70 |       constexpr size_type
      |                 ^~~~~~~~~
c:\users\ilya\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.1.0-gcc10.3-e5f9fec\xtensa-lx106-elf\include\c++\10.3.0\initializer_list:47:11: fatal error: definition of 'class std::initializer_list<_E>' does not match '#include <initializer_list>'
   47 |     class initializer_list
      |           ^~~~~~~~~~~~~~~~
compilation terminated.`

версия пакета плат esp8266: 3.1.2
плата: LOLIN(WEMOS) D1 R2 & mini

**Comment by IlyaDudelzak** [comment]
Версия Arduino IDE: 1.8.13

**Comment by GyverLibs** [comment]
Проверь без <WS2812FX.h>

**Comment by IlyaDudelzak** [comment]
То же самое.
Я сейчас на втором компьютере, проблема та же.

**Comment by IlyaDudelzak** [comment]
А вот когда все в одну вкладку...

**Comment by IlyaDudelzak** [comment]
Wrote 496128 bytes (361148 compressed) at 0x00000000 in 8.3 seconds (effective 479.7 kbit/s)...
