### ISSUE TITLE
Не отображается устройство

### ISSUE THREAD

**Issue by l524l** [GyverLibs/GyverHub#47]
Пытаюсь подключить стандартный пример по mqtt но не вижу устройство

вот пример настройки и кода
![Снимок экрана 2024-06-08 142028](https://github.com/GyverLibs/GyverHub/assets/65085630/12c96619-9432-4e31-b1f4-29e9fc9d54be)
![Снимок экрана 2024-06-08 142101](https://github.com/GyverLibs/GyverHub/assets/65085630/0f7f73a3-fc33-4e0f-912a-0b836ac824c6)

**Comment by GyverLibs** [comment]
внимательнее читать документацию, там ведь всё написано
