### ISSUE TITLE
Библиотеки нет в Library manager

### ISSUE THREAD

**Issue by c0dd3vi11** [GyverLibs/GyverHub#48]
По ссылке https://search.arduino.cc/search?tab=reference&q=GyverHub и в самой Adruino IDE нет библиотеки GyverHub в менеджере библиотек. Документация устарела:
- https://github.com/GyverLibs/GyverHub/blob/main/docs/2.start.md - тут упоминание "При установке GyverHub из реестра все библиотеки установятся автоматически"
- https://github.com/GyverLibs/GyverHub/tree/main - тут: Через менеджер библиотек IDE: найти библиотеку как при установке и нажать "Обновить"

Кстати, почему ее нет? Может это можно починить?

**Comment by GyverLibs** [comment]
Библиотека в разработке, в менеджере её нет
