### ISSUE TITLE
GyverHUB алгоритм поиска устройств в локальной сети

### ISSUE THREAD

**Issue by nikelcase** [GyverLibs/GyverHub#5]
Доработал GyverHUB сайт скачиваемый по ссылке [https://hub.gyver.ru/GyverHUB.zip](https://hub.gyver.ru/GyverHUB.zip) в плане корректного алгоритма поиска устройств в локальной сети. Внешний вид блока local в доработке выглядит так:
![local](https://github.com/GyverLibs/GyverHUB/assets/14200751/eb432ae6-48b0-4f1d-80cf-d6ada0014b75)
![expanded](https://github.com/GyverLibs/GyverHUB/assets/14200751/770a2bc9-61dc-4123-8c77-007c0de3f7a6)
Реализация (если Add by IP пуст, то вызывается функция http_discover_all)
main.js блок local
```
      <div class="cfg_col">
        <div class="cfg_row cfg_head">
          <label><span class="icon cfg_icon"></span> Local</label>
          <label class="switch"><input type="checkbox" id="use_local" onchange="update_cfg(this)"><span class="slider"></span></label>
        </div>

        <div id="http_block" style="display:none">
          <div class="cfg_row" id="http_only_http">
            <span style="color:#c60000">Works only on <strong class="span_btn" onclick="window.location.href = window.location.href.replace('https', 'http')">HTTP</strong>!</span>
          </div>

          <div id="http_settings" style="display:none">
            <div class="cfg_row">
              <label>My IP</label>
              <div class="cfg_inp_row">
                <input class="cfg_inp" type="text" id="http_ip" onchange="update_cfg(this)">
                <div class="cfg_btn_block">
                  <button class="icon cfg_btn" onclick="update_ip();update_cfg(EL('http_ip'))"></button>
                </div>
              </div>
            </div>

            <div class="cfg_row">
              <label>Add by IP</label>
              <div class="cfg_inp_row">
                <input class="cfg_inp" type="text" value="192.168.1.1" id="http_manual_ip">
                <div class="cfg_btn_block">
                  <button class="icon cfg_btn" onclick="manual_h()"></button>
                </div>
              </div>
            </div>
            
            <div class="cfg_row">
              <label>Netmask</label>
              <div class="cfg_inp_row">
                <select class="cfg_inp c_inp_block" id="netmask" onchange="update_cfg(this)">
                  <option value="0">0 - 0.0.0.0</option>
                  <option value="1">1 - 128.0.0.0</option>
                  <option value="2">2 - 192.0.0.0</option>
                  <option value="3">3 - 224.0.0.0</option>
                  <option value="4">4 - 240.0.0.0</option>
                  <option value="5">5 - 248.0.0.0</option>
                  <option value="6">6 - 252.0.0.0</option>
                  <option value="7">7 - 254.0.0.0</option>
                  <option value="8">8 - 255.0.0.0</option>
                  <option value="9">9 - 255.128.0.0</option>
                  <option value="10">10 - 255.192.0.0</option>
                  <option value="11">11 - 255.224.0.0</option>
                  <option value="12">12 - 255.240.0.0</option>
                  <option value="13">13 - 255.248.0.0</option>
                  <option value="14">14 - 255.252.0.0</option>
                  <option value="15">15 - 255.254.0.0</option>
                  <option value="16">16 - 255.255.0.0</option>
                  <option value="17">17 - 255.255.128.0</option>
                  <option value="18">18 - 255.255.192.0</option>
                  <option value="19">19 - 255.255.224.0</option>
                  <option value="20">20 - 255.255.240.0</option>
                  <option value="21">21 - 255.255.248.0</option>
                  <option value="22">22 - 255.255.252.0</option>
                  <option value="23">23 - 255.255.254.0</option>
                  <option value="24" selected>24 - 255.255.255.0</option>
                  <option value="25">25 - 255.255.255.128</option>
                  <option value="26">26 - 255.255.255.192</option>
                  <option value="27">27 - 255.255.255.224</option>
                  <option value="28">28 - 255.255.255.240</option>
                  <option value="29">29 - 255.255.255.248</option>
                  <option value="30">30 - 255.255.255.252</option>
                  <option value="31">31 - 255.255.255.254</option>
                  <option value="32">32 - 255.255.255.255</option>
                </select>
              </div>
            </div>
            <span class="notice_block">Disable: <u>${browser()}://flags/#block-insecure-private-network-requests</u></span>
          </div>
        </div>
      </div>

```
connection.js функции manual_h, http_discover_all и вспомогательные
```
function http_discover_ip(str_ip) {
  http_send("http://" + str_ip + ":" + http_port + "/" + cfg.prefix);
}
function ip_to_text_and_send(int_ip) {
  let o1 = (int_ip >>> 24) & 0x000000ff;
  let o2 = (int_ip >>> 16) & 0x000000ff;
  let o3 = (int_ip >>> 8) & 0x000000ff;
  let o4 = int_ip & 0x000000ff;
  let result = ''.concat(o1.toString(10), '.', o2.toString(10), '.', o3.toString(10), '.', o4.toString(10));
  setTimeout(() => {
      http_discover_ip(result);
  }, 10 * (Math.floor(Math.random() * 255) + 1));
  //log(result);
}
function parse_octet(x) {
  let parsed = parseInt(x, 10);
  if (isNaN(parsed)) { return -1; }
  if (parsed < 0 || parsed > 255) { return -1; }
  return parsed;
}
function http_discover_all() {
  log('Begin HTTP discover all');
  let clr_ip = EL('http_ip').value.trim().replaceAll(',', '.');  //192,168,1,1 -> 192.168.1.1 (numpad, ru lang)
  if (!clr_ip) { // strValue was empty string, false, 0, null, undefined, ...
    log('Invalid IP address in "My IP"');
    log('End HTTP discover all');
    return;
  }
  let is_correct = Boolean(clr_ip.match(/^[0-9\.]+$/));
  if (!is_correct) {
    log('Invalid IP address in "My IP"');
    log('End HTTP discover all');
    return;
  }
  let ip_a = clr_ip.split('.');
  let octet1 = 0, octet2 = 0, octet3 = 0, octet4 = 0;
  switch (ip_a.length) {
    case 1:
      octet4 = parseInt(ip_a[0], 10);
      if (isNaN(octet4) || octet4 < 0 || octet4 > 0xffffffff) {
        log('Invalid IP address in "My IP"');
        log('End HTTP discover all');
        return;
      }
      if (octet4 < 256) { break; }
      octet1 = (octet4 >>> 24) & 0x000000ff
      octet2 = (octet4 >>> 16) & 0x000000ff
      octet3 = (octet4 >>> 8) & 0x000000ff
      octet4 = octet4 & 0x000000ff
      break;
    case 2:
      octet1 = parse_octet(ip_a[0]);
      octet4 = parse_octet(ip_a[1]);
      if (octet1< 0 || octet4 < 0) {
        log('Invalid IP address in "My IP"');
        log('End HTTP discover all');
        return;
      }
      break;
    case 3:
      octet1 = parse_octet(ip_a[0]);
      octet2 = parse_octet(ip_a[1]);
      octet4 = parse_octet(ip_a[2]);
      if (octet1 < 0 || octet2 < 0 || octet4 < 0) {
        log('Invalid IP address in "My IP"');
        log('End HTTP discover all');
        return;
      }
      break;
    case 4:
      octet1 = parse_octet(ip_a[0]);
      octet2 = parse_octet(ip_a[1]);
      octet3 = parse_octet(ip_a[2]);
      octet4 = parse_octet(ip_a[3]);
      if (octet1 < 0 || octet2 < 0 || octet3 < 0 || octet4 < 0) {
        log('Invalid IP address in "My IP"');
        log('End HTTP discover all');
        return;
      }
      break;
    default:
      log('Invalid IP address in "My IP"');
      log('End HTTP discover all');
      return;
  }
  let cidr = parseInt(EL('netmask').value.trim(), 10);
  if (isNaN(cidr) || cidr < 0 || cidr > 32) {
    log('Invalid netmask');
    log('End HTTP discover all');
    return;
  }
  let mask = ~(0xffffffff >>> cidr);
  let sum_ip = (octet1 << 24) | (octet2 << 16) | (octet3 << 8) | octet4;
  let network = 0, broadcast = 0, start_ip = 0, end_ip = 0;
  if (cidr === 32) {
    network = sum_ip;
    broadcast = network;
    start_ip = network;
    end_ip = network;
  } else {
    network = sum_ip & mask;
    broadcast = network + (~mask);
    if (cidr === 31) {
      start_ip = network;
      end_ip = broadcast;
    } else {
      start_ip = network + 1;
      end_ip = broadcast - 1;
    }
  }
  for (let i = start_ip; i <= end_ip; i++) {
    ip_to_text_and_send(i)
  }
  log('End HTTP discover all');
}
function manual_h() {
  let mip = EL('http_manual_ip').value;
  mip = mip.trim(); //remove spaces
  mip = mip.replaceAll(',', '.') //192,168,1,1 -> 192.168.1.1 (numpad, ru lang)
  log('HTTP manual ' + mip);
  if (!mip) { // strValue was empty string, false, 0, null, undefined, ...
    http_discover_all();
  } else {
    http_discover_ip(mip);
  }
  back_h();
}

```
они же файлами
[main.js_local_block.txt](https://github.com/GyverLibs/GyverHUB/files/11490606/main.js_local_block.txt)
[connection.js_manual_h_and_http_discover_ip_edit.txt](https://github.com/GyverLibs/GyverHUB/files/11490608/connection.js_manual_h_and_http_discover_ip_edit.txt)

**Comment by maleksware** [comment]
Думаю, правильно будет сделать pull request в ветку фикса.

**Comment by GyverLibs** [comment]
А что это за набор масок? Какие-то то стандартные диапазоны?

**Comment by nikelcase** [comment]
> А что это за набор масок? Какие-то то стандартные диапазоны?

Это все доступные маски для IPv4 - [CIDR](https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%81%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2%D0%B0%D1%8F_%D0%B0%D0%B4%D1%80%D0%B5%D1%81%D0%B0%D1%86%D0%B8%D1%8F)
По хорошему поле netmask вывести к глобальным настройкам в связи с тем, что кнопка find new devices вызывает функцию http_discover_all()

Еще, т.к. тип number в js 32 битный, то в switch -> case 1 строку if (isNaN(octet4) || octet4 < 0 || octet4 > 0xffffffff) { нужно заменить на if (isNaN(octet4)) { и if (octet4 < 256) { break; } на if (octet4 < 256 && octet4 >=0) { break; }

**Comment by GyverLibs** [comment]
Круто, спасибо! Думаю вынести отдельно сетевые настройки и добавить отдельное обнаружение чисто по websocket. Тогда как раз можно использовать предложенный алгоритм поиска диапазона адресов по маске! Буду у компьютера, всё попробую, отпишу. 

Общий дискавер из кнопки добавления по ip лучше убрать, интуитивно непонятно что эта кнопка может вызывать ддос роутера :)

**Comment by GyverLibs** [comment]
> Думаю, правильно будет сделать pull request

К чему? В репозитории нет сайта

**Comment by nikelcase** [comment]
> Круто, спасибо! Думаю вынести отдельно сетевые настройки и добавить отдельное обнаружение чисто по websocket. Тогда как раз можно использовать предложенный алгоритм поиска диапазона адресов по маске! Буду у компьютера, всё попробую, отпишу.
> 
> Общий дискавер из кнопки добавления по ip лучше убрать, интуитивно непонятно что эта кнопка может вызывать ддос роутера :)

В релизе с полем netmask нужно будет сделать то же, что и с полем main color, чтобы selected оставался на нужной маске при перезапуске.

И в дополнение можно периодически слать запросы на какой-либо multicast (лучше) адрес или broadcast (хуже) в поисках таких-же сайтов на других устройствах в сети и синхронизировать их.

**Comment by GyverLibs** [comment]
Сохранение конечно, это одну строчку добавить) по broad/multicast не понял

**Comment by nikelcase** [comment]
Все примеры для локального использования

Пример 1: GyverHUB запущен на двух телефонах, на одном все настроено, на другом еще нет и не хотелось бы все заново настраивать на другом телефоне (много устройств). Они должны как-то найти друг друга, ip им раздает роутер динамически (как с лампами тут не выйдет), каждый раз опрашивать при маске 255.255.255.0 все 254 устройства долго, тут будет проще слушать broadcast или multicast адреса в которых ждать запроса (как в dhcp) по типу "я хочу настроек, мой адрес такой-то)

Пример 2: Так же есть два телефона, одним управляют освещением, второй просто лежит, как на втором телефоне отобразить состояние выключателя? "Умному" устройству неважно кто отправил запрос, он ответит обратно либо широковещательно, но например если делать устройство на enc28j60, то он не умеет нормально работать с мультикастом (правда пробовал я это последний раз пару лет назад, на сейчас какая ситуация не знаю), поэтому телефону будет проще после ответа от датчика разослать его состояние другим телефонам, найденным как в предыдущем примере и сохраненным в какой-либо список у себя

**Comment by nikelcase** [comment]
Для тех, кто хотел бы немного разобраться почему IPv4 это 4 блока цифр разделенных точками, а в коде switch, который допускает от одной до четырех цифр и еще немного в коде.

Допустимо указывать IPv4 от одной до четырех цифр (с некоторыми ограничениями, см. примеры), главное чтобы после операции | (побитового или) над этими числами результат был в пределе от 0x00000000 до 0xfffffffe (от 0 до 4294967294, (2^32)-2, не может быть отрицательным)
Допустимы десятичные числа, восьмеричные (с префиксным нулем) и шестнадцатеричные (с префиксом 0x)
Пример google chrome
![chrome](https://github.com/GyverLibs/GyverHUB/assets/14200751/95f58027-cbc9-4491-b55e-3cb84c75235f)

или утилита командной строки ping (допустимые варианты, все отсутствующие числа заменяются нулями)
![ping1](https://github.com/GyverLibs/GyverHUB/assets/14200751/26874423-8706-4d93-acc9-966e2113c786)
![ping2](https://github.com/GyverLibs/GyverHUB/assets/14200751/998581f0-4cbe-42b4-826a-955664121ffb)
![ping3](https://github.com/GyverLibs/GyverHUB/assets/14200751/29a6f443-e543-490c-93d6-c875897b3302)
![ping4](https://github.com/GyverLibs/GyverHUB/assets/14200751/ed40453f-bcd1-4cd4-af35-a26c919f7b29)
![ping5](https://github.com/GyverLibs/GyverHUB/assets/14200751/c7b605a9-8108-4ae3-959e-f899d59ce668)
![ping6](https://github.com/GyverLibs/GyverHUB/assets/14200751/c8af5f15-3cd0-44af-881c-6dd1848411f3)
![ping9](https://github.com/GyverLibs/GyverHUB/assets/14200751/aa6fa1f1-490e-4007-9fa5-186e1d80ff24)
![ping12](https://github.com/GyverLibs/GyverHUB/assets/14200751/2c385b04-652f-41ab-b6ef-c33fbff25b0f)
![ping13](https://github.com/GyverLibs/GyverHUB/assets/14200751/3a275275-bd38-44f7-977a-623573a00874)
![ping14](https://github.com/GyverLibs/GyverHUB/assets/14200751/d25531c5-1304-427b-b484-11c4640c59bf)

и не допустимые
![ping11](https://github.com/GyverLibs/GyverHUB/assets/14200751/dff9157a-b817-4d22-8af2-7641ff90214f)
![ping 10](https://github.com/GyverLibs/GyverHUB/assets/14200751/4dc60ea9-c1c0-4930-8cb9-281e12442e58)
![ping7](https://github.com/GyverLibs/GyverHUB/assets/14200751/cdef18f3-83b9-4adc-a691-e92eb15be9c9)

Задача копирования данного поведения полностью не стояла, при желании можете самостоятельно попробовать его реализовать в качестве тренировкой по операциям с битами
В коде шестнадцатеричные числа убирает строка let is_correct = Boolean(clr_ip.match(/^[0-9\.]+$/)); (точнее сказать пропускает строку состоящую из цифр от 0 до 9 и знака точка)
Если будут присланы значения в восьмеричной системе счисления, то они будут преобразованы как десятичные этой строкой let parsed = parseInt(x, 10);
В данном преобразовании (int_ip >>> 24) & 0x000000ff; и подобных операция & с числом 0x000000ff нужна в качестве предохранителя в случае, если вместо сдвига >>> с заполнением нулями, будет сдвиг >> с заполнением знаковым битом (кто-то опечатался и вместо нулей будут единицы, что в итоге приведет к отрицательному числу)
А в остальном - if как защита от ненужных нам значений (например в if (isNaN(cidr) || cidr < 0 || cidr > 32) хоть у нас и есть точные значения, но возможна и опечатка и для контроля этого  cidr < 0 || cidr > 32)  и операции с битами для получения диапазона нужных

Все примеры делались на компьютере под управлением Windows, можете их попробовать у себя

**Comment by GyverLibs** [comment]
Я бы принудил к десятичному вводу с точками, чтобы не перегружать дополнительным кодом 😀 😅

по поводу передачи настроек - как то замудрено получается... Настройки можно передать через импорт экспорт, а бродкаст с устройства реализован через вебсокет - нативно отправит новые данные всем клиентам.

**Comment by nikelcase** [comment]
Десятичный с точками реализовывается оставлением секций case 4 и default в switch или замена его на if, я хотел показать, что и так корректно

А по передачи настроек и состояния - просто как альтернатива, чтобы не тащить все на более высокие уровни сетевого взаимодействия

**Comment by GyverLibs** [comment]
Сократил до вот такого
```cpp
function checkIP(ip) {
  return Boolean(ip.match(/^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\.(?!$)|$)){4}$/));
}
function intToOctets(ip) {
  let o1 = (ip >>> 24) & 0xff;
  let o2 = (ip >>> 16) & 0xff;
  let o3 = (ip >>> 8) & 0xff;
  let o4 = ip & 0xff;
  return (o1 + '.' + o2 + '.' + o3 + '.' + o4);
}
function getIPs() {
  let ip = EL('http_ip').value;
  if (!checkIP(ip)) {
    showPopupError('Wrong IP!');
    return null;
  }
  let ip_a = ip.split('.');
  let sum_ip = (ip_a[0] << 24) | (ip_a[1] << 16) | (ip_a[2] << 8) | ip_a[3];
  let cidr = Number(EL('netmask').value);
  let mask = ~(0xffffffff >>> cidr);
  let network = 0, broadcast = 0, start_ip = 0, end_ip = 0;
  if (cidr === 32) {
    network = sum_ip;
    broadcast = network;
    start_ip = network;
    end_ip = network;
  } else {
    network = sum_ip & mask;
    broadcast = network + (~mask);
    if (cidr === 31) {
      start_ip = network;
      end_ip = broadcast;
    } else {
      start_ip = network + 1;
      end_ip = broadcast - 1;
    }
  }
  let ips = [];
  for (let ip = start_ip; ip <= end_ip; ip++) {
    ips.push(intToOctets(ip));
  }
  return ips;
}
```

Получаю массив айпишников и дальше по нему работаю в нужных местах
