### ISSUE TITLE
Если в main.ino установлено #define GH_NO_MQTT, почему оно не проверяется в GyverHub.h? 

### ISSUE THREAD

**Issue by AndreiKorchunov** [GyverLibs/GyverHub#7]
Я не собираюсь использовать MQTT в full_demo.ino, поэтому раскомментировал  #define GH_NO_MQTT. Не смотря на это мне выпадает ошибка: 
![image](https://github.com/GyverLibs/GyverHub/assets/122872898/83173ad8-0b69-45e2-9b3a-0711384c1484)
При изучении кода видно, что подключение внешних библиотек не учитывает наличие define GH_NO_MQTT и прочих аналогичных.
![image](https://github.com/GyverLibs/GyverHub/assets/122872898/c6169485-ba6f-4e81-9ae6-3d47109dd231)
Получается, что, не смотря на явный запрет использования MQTT, библиотека для него все равно подключается к проекту для чего мне приходится ее скачивать и и инсталлировать в ARDUINO IDE.
Хотелось бы, что наличие define учитывалось в include бибилиотек.

**Comment by GyverLibs** [comment]
> не смотря на явный запрет использования MQTT, библиотека для него все равно подключается к проекту

стрелочкой указана не библиотека MQTT, это файл GyverHub и проверка на использование MQTT идёт уже внутри него. Но ошибка в работе GH_NO_MQTT действительно есть, сейчас исправлю

**Comment by AndreiKorchunov** [comment]
Спасибо за быструю реакцию.
