### ISSUE TITLE
Проблема с иконками в приложении и браузере

### ISSUE THREAD

**Issue by waw555** [GyverLibs/GyverHub#9]
Здравствуйте! 

Возможно это только у меня, но в приложении и браузере некоторые иконки не отображаются или отображаются по разному.

NODEMCU
Браузер Google Chrome
Залит пример full_demo

![Screenshot_20230721_221108](https://github.com/GyverLibs/GyverHub/assets/1402355/6c47b31e-080d-466a-85c8-a17bd5ebd4a2)
![Screenshot_20230721_221114](https://github.com/GyverLibs/GyverHub/assets/1402355/fe9bc927-5918-4e1c-ba73-125a3cf9598a)
![2023-07-21_22-09-55](https://github.com/GyverLibs/GyverHub/assets/1402355/6656d445-6dce-4a9b-b174-6354a44e0613)
![2023-07-21_22-10-24](https://github.com/GyverLibs/GyverHub/assets/1402355/0e11187d-812b-4d7e-9a1d-d7db33d9b7ed)

**Comment by GyverLibs** [comment]
При загрузке сайта из памяти есп работают только системные иконки, а остальные заменяются на стандартные. Но как я вижу заменились не везде, в следующем обновлении пофикшу. Есп версия вообще особо не тестировалась на данный момент

**Comment by GyverLibs** [comment]
пофикшено
